"""
Semantic placement targets generated by the Plan Builder.
"""

from __future__ import annotations

import json
import shutil
import subprocess
from dataclasses import dataclass
from pathlib import Path

import pytest
from typing_extensions import Any

from coraplex.datastructures.enums import Arms
from coraplex.robot_plans.actions.composite.transporting import TransportAction
from cramera.paths import WEB_ROOT
from cramera.live.placement_surface import PlacementSurface
from semantic_digital_twin.semantic_annotations.semantic_annotations import Milk, Table
from semantic_digital_twin.spatial_types import HomogeneousTransformationMatrix
from semantic_digital_twin.spatial_types.spatial_types import Pose
from semantic_digital_twin.world import World
from semantic_digital_twin.world_description.geometry import Scale
from semantic_digital_twin.world_description.world_entity import Body

# %% placement scene


@dataclass
class PlacementScene:
    """
    A supported placement area and a movable object.
    """

    world: World
    """World containing the object and placement surface."""

    surface: Table
    """
    The annotated supporting table.
    """

    object: Milk
    """The object to transport onto the table."""


@pytest.fixture
def placement_scene(world_with_two_bodies: tuple[World, Body, Body]) -> PlacementScene:
    """
    Build a placement scene in the existing empty-world fixture.

    :param world_with_two_bodies: A fresh world and its unconnected bodies.
    """
    world, root, _ = world_with_two_bodies
    with world.modify_world():
        world.add_body(root)
        surface = Table.create_with_new_body_in_world(
            name="table", world=world, scale=Scale(2.0, 2.0, 0.1)
        )
        object = Milk.create_with_new_body_in_world(
            name="milk",
            world=world,
            scale=Scale(0.08, 0.08, 0.2),
            world_root_T_self=HomogeneousTransformationMatrix.from_xyz_rpy(x=3),
        )
    return PlacementScene(world, surface, object)


# %% generated plan integration


@dataclass(init=False, eq=False)
class TestGeneratedSemanticPlacement:
    """
    Generated actions accept raw world bodies and ground their semantic target.
    """

    def test_transport_accepts_an_annotated_surface(
        self, placement_scene: PlacementScene
    ) -> None:
        """
        Resolve a generated Transport without entering an exact target pose.

        :param placement_scene: A world with an annotated table and movable object.
        """
        executable = shutil.which("node")
        if executable is None:
            pytest.skip("Node.js is required to execute the browser's generator")
        result = subprocess.run(
            [
                executable,
                str(Path(__file__).parent / "dataset" / "generate_semantic_plan.js"),
                str(WEB_ROOT),
            ],
            input=json.dumps(
                {
                    "id": "placement",
                    "type": "transport",
                    "params": {
                        "object": str(placement_scene.object.root.name),
                        "arm": Arms.LEFT.name,
                        "targetMode": "semantic",
                        "surfaceType": Table.__name__,
                        "surfaceName": str(placement_scene.surface.root.name),
                    },
                }
            ),
            text=True,
            capture_output=True,
            check=True,
        )
        generated = json.loads(result.stdout)
        namespace: dict[str, Any] = {
            "world": placement_scene.world,
            "Pose": Pose,
            "TransportAction": TransportAction,
            "Arms": Arms,
        }
        exec(generated["setup"], namespace)
        action = eval(generated["action"], namespace)
        assert isinstance(action, TransportAction)
        assert action.object_designator is placement_scene.object.root
        assert isinstance(action.target_location, PlacementSurface)
        assert isinstance(next(iter(action.target_location)), Pose)
