"""Generated by the cramera Plan Builder."""
import os
from coraplex.datastructures.dataclasses import Context
from coraplex.datastructures.enums import Arms, VisualizationBackend
from coraplex.execution_environment import simulated_robot
from coraplex.plans.factories import sequential
from coraplex.visualization import WorldVisualization
from coraplex.robot_plans.actions.composite.transporting import TransportAction
from coraplex.robot_plans.actions.core.navigation import NavigateAction
from coraplex.robot_plans.actions.core.robot_body import ParkArmsAction, MoveTorsoAction
from semantic_digital_twin.adapters.mesh import DAEParser, OBJParser, STLParser
from semantic_digital_twin.adapters.urdf import URDFParser
from semantic_digital_twin.datastructures.definitions import TorsoState
from semantic_digital_twin.reasoning.world_reasoner import WorldReasoner
from semantic_digital_twin.robots.pr2 import PR2
from semantic_digital_twin.spatial_types import HomogeneousTransformationMatrix
from semantic_digital_twin.spatial_types.spatial_types import Pose
from semantic_digital_twin.world_description.geometry import Color

_HERE = os.path.dirname(__file__)
_WORLDS = os.path.join(_HERE, "..", "..", "resources", "worlds")
_OBJECTS = os.path.join(_HERE, "..", "..", "resources", "objects")
_MESH_PARSERS = {".stl": STLParser, ".obj": OBJParser, ".dae": DAEParser}


def _parse_mesh(mesh):
    """Parse an object mesh into a world, picking the parser by file extension."""
    ext = os.path.splitext(mesh)[1].lower()
    return _MESH_PARSERS.get(ext, STLParser)(os.path.join(_OBJECTS, mesh)).parse()


def build_world(env_file, robot_xy):
    """Parse the chosen environment + PR2 and spawn the robot at robot_xy."""
    robot_world = URDFParser.from_file(PR2.get_ros_file_path()).parse()
    world = URDFParser.from_file(os.path.join(_WORLDS, env_file)).parse()
    with world.modify_world():
        robot_root = robot_world.get_body_by_name(PR2._get_root_body_name())
        drive = PR2.get_drive_connection_type().create_with_dofs(
            parent=world.root, child=robot_root, world=world)
        world.merge_world(robot_world, drive)
        drive.origin = HomogeneousTransformationMatrix.from_xyz_rpy(robot_xy[0], robot_xy[1], 0)
    standing = max(0.0, -world.height_of_lowest_collision_point_of_branch(robot_root))
    with world.modify_world():
        drive.parent_T_connection_expression = HomogeneousTransformationMatrix.from_xyz_rpy(
            z=standing, reference_frame=world.root)
    return world


world = build_world("apartment.urdf", (1.5, 2.5))
visualization = WorldVisualization.from_environment(
    world, default_backend=VisualizationBackend.CRAMERA).start()

# --- objects placed in the Plan Builder ---
_obj0 = _parse_mesh("milk.stl")
_obj1 = _parse_mesh("bowl.stl")
with world.modify_world():
    world.merge_world_at_pose(_obj0, HomogeneousTransformationMatrix.from_xyz_rpy(
        1.62, 2.5, 1.9, roll=0, pitch=0, yaw=0, reference_frame=world.root))
    world.merge_world_at_pose(_obj1, HomogeneousTransformationMatrix.from_xyz_rpy(
        1.412, 2.581, 2.06, roll=0, pitch=0, yaw=0, reference_frame=world.root))
world.get_body_by_name("milk.stl").visual.shapes[0].color = Color(0.6, 0.63, 0.68)
world.get_body_by_name("bowl.stl").visual.shapes[0].color = Color(0.56, 0.84, 0.78)

robot = PR2.from_world(world)
context = Context(world=world, robot=robot, _debug=False, ros_node=visualization.ros_node)
with world.modify_world():
    WorldReasoner(world).reason()
context.evaluate_conditions = False

plan = sequential([
    ParkArmsAction(Arms.BOTH),
], context=context).plan
visualization.attach_plan(plan)

with simulated_robot:
    plan.perform()
