"""Generated by the cramera Plan Builder — a RobotDemonstration subclass."""
import os
from dataclasses import dataclass

from coraplex.datastructures.dataclasses import Context
from coraplex.datastructures.enums import Arms, VisualizationBackend
from coraplex.datastructures.grasp import GraspDescription
from coraplex.demonstrations import RobotDemonstration
from coraplex.plans.factories import sequential
from coraplex.plans.plan_node import PlanNode
from coraplex.robot_plans.actions.composite.transporting import TransportAction
from coraplex.robot_plans.actions.core.navigation import NavigateAction
from coraplex.robot_plans.actions.core.pick_up import PickUpAction
from coraplex.robot_plans.actions.core.placing import PlaceAction
from coraplex.robot_plans.actions.core.robot_body import ParkArmsAction, MoveTorsoAction
from coraplex.view_manager import ViewManager
from semantic_digital_twin.api import (
    BodySpecification,
    Connection6DoFSpecification,
    RobotSpecification,
    WorldSpecification,
)
from semantic_digital_twin.datastructures.definitions import TorsoState
from semantic_digital_twin.reasoning.world_reasoner import WorldReasoner
from semantic_digital_twin.robots.robot_part_mixins import HasMobileBase
from semantic_digital_twin.robots.garmi import Garmi
from semantic_digital_twin.spatial_types import HomogeneousTransformationMatrix
from semantic_digital_twin.spatial_types.spatial_types import Pose
from semantic_digital_twin.world import World
from semantic_digital_twin.world_description.geometry import Color

_HERE = os.path.dirname(__file__)
_WORLDS = os.path.join(_HERE, "..", "..", "resources", "worlds")
_OBJECTS = os.path.join(_HERE, "..", "..", "resources", "objects")

ENV_FILE = "warehouse6.urdf"
ROBOT_XY = (1.5, 2.5)
# whether the base may drive to help an arm reach (whole-body control). A plan
# built in the Plan Builder says where the robot stands, with its Navigate steps.
BASE_MAY_DRIVE_WHILE_REACHING = False

# objects placed in the Plan Builder: (mesh, x, y, z, roll, pitch, yaw, (r, g, b))
OBJECTS = [
    ("milk.stl", 2.35, -0.05, 0.71, 0, 0, 0, (0.6, 0.63, 0.68)),
    ("bowl.stl", 2.56, -0.72, 0.65, 0, 0, 0, (0.56, 0.84, 0.78)),
]


@dataclass(kw_only=True)
class MyDemoDemonstration(RobotDemonstration):
    """A demonstration composed in the cramera Plan Builder."""

    def build_simulated_world(self) -> World:
        return WorldSpecification.from_urdf(
            os.path.join(_WORLDS, ENV_FILE),
            robots=[
                RobotSpecification(
                    semantic_annotation_type=self.used_robot,
                    world_T_odom=HomogeneousTransformationMatrix.from_xyz_rpy(
                        ROBOT_XY[0], ROBOT_XY[1], 0.0),
                ),
            ],
        ).to_domain_object()

    def is_scene_populated(self, world: World) -> bool:
        for spec in OBJECTS:
            try:
                world.get_body_by_name(spec[0])
            except Exception:
                return False
        return bool(OBJECTS)

    def populate_scene(self, world: World) -> None:
        # each object is free to move (Connection6DoF), so the robot can transport it
        for mesh, x, y, z, roll, pitch, yaw, rgb in OBJECTS:
            BodySpecification.mesh(
                mesh,
                os.path.join(_OBJECTS, mesh),
                color=Color(*rgb),
                parent_T_self=HomogeneousTransformationMatrix.from_xyz_rpy(
                    x, y, z, roll=roll, pitch=pitch, yaw=yaw),
                connection_specification=Connection6DoFSpecification(),
            ).spawn(world)

    def build_context(self, world: World) -> Context:
        with world.modify_world():
            WorldReasoner(world).reason()
        robot = world.get_semantic_annotations_by_type(self.used_robot)[0]
        if isinstance(robot, HasMobileBase):
            robot.mobile_base.full_body_controlled = BASE_MAY_DRIVE_WHILE_REACHING
        context = Context(world=world, robot=robot, _debug=False, ros_node=self.ros_node)
        context.evaluate_conditions = False
        return context

    def build_plan(self, context: Context) -> PlanNode:
        world = context.world  # bodies/poses below are resolved against it
        # pick "milk.stl" with the left arm
        _pick_s4 = world.get_body_by_name("milk.stl")
        _grasp_s4 = GraspDescription.robot_relative_default(
            ViewManager.get_end_effector_view(Arms.LEFT, context.robot),
            _pick_s4.global_pose,
            _pick_s4,
        )
        return sequential([
            NavigateAction(Pose.from_xyz_rpy(1.4, -0.29, 0, yaw=0, reference_frame=world.root)),
            ParkArmsAction(Arms.BOTH),
            MoveTorsoAction(TorsoState.MID),
            PickUpAction(_pick_s4, Arms.LEFT, _grasp_s4),
            ParkArmsAction(Arms.BOTH),
            MoveTorsoAction(TorsoState.MID),
            NavigateAction(Pose.from_xyz_rpy(5.73, -1.76, 0, yaw=1.55, reference_frame=world.root)),
            PlaceAction(world.get_body_by_name("milk.stl"), Pose.from_xyz_rpy(5.64, -0.93, 0.74, yaw=1.623, reference_frame=world.root), Arms.LEFT),
        ], context=context).plan


def main() -> None:
    """Run the demonstration.

    RobotDemonstration.run() acquires the world, starts the visualization backend,
    attaches the plan and performs it. The backend defaults to CRAMERA (the browser
    viewer); CORAPLEX_VISUALIZATION overrides it, so `cramera-live` works unchanged
    and you can also force RVIZ / NONE from the outside.
    """
    MyDemoDemonstration(
        used_robot=Garmi,
        collision_avoidance=True,
        default_visualization_backend=VisualizationBackend.CRAMERA,
    ).run()


if __name__ == "__main__":
    main()
