"""
Generated by the cramera Plan Builder.
"""

import os
from coraplex.datastructures.dataclasses import Context
from coraplex.datastructures.enums import Arms, VisualizationBackend
from coraplex.datastructures.grasp import GraspDescription
from coraplex.execution_environment import simulated_robot_advanced
from coraplex.plans.factories import sequential
from coraplex.visualization import WorldVisualization
from coraplex.robot_plans.actions.composite.transporting import TransportAction
from coraplex.robot_plans.actions.core.navigation import NavigateAction
from coraplex.robot_plans.actions.core.pick_up import PickUpAction
from coraplex.robot_plans.actions.core.placing import PlaceAction
from coraplex.robot_plans.actions.core.robot_body import ParkArmsAction, MoveTorsoAction
from coraplex.view_manager import ViewManager
from semantic_digital_twin.adapters.mesh import DAEParser, OBJParser, STLParser
from semantic_digital_twin.api import RobotSpecification, WorldSpecification
from semantic_digital_twin.datastructures.definitions import TorsoState
from semantic_digital_twin.reasoning.world_reasoner import WorldReasoner
from cramera.live.placement_annotations import PlacementAnnotations
from semantic_digital_twin.robots.robot_part_mixins import HasMobileBase
from semantic_digital_twin.robots.pr2 import PR2
from cramera.multi_robot import RobotInstance, RobotScene
from semantic_digital_twin.spatial_types import HomogeneousTransformationMatrix
from semantic_digital_twin.spatial_types.spatial_types import Pose
from semantic_digital_twin.world import World
from semantic_digital_twin.world_description.geometry import Color

_HERE = os.path.dirname(__file__)
_WORLDS = os.path.join(_HERE, "..", "..", "resources", "worlds")
_OBJECTS = os.path.join(_HERE, "..", "..", "resources", "objects")
_MESH_PARSERS = {".stl": STLParser, ".obj": OBJParser, ".dae": DAEParser}


def _parse_mesh(mesh: str) -> World:
    """
    Parse an object mesh into its own world.

    :param mesh: Object filename in the installed mesh directory.
    :return: World containing the parsed object.
    """
    ext = os.path.splitext(mesh)[1].lower()
    return _MESH_PARSERS.get(ext, STLParser)(os.path.join(_OBJECTS, mesh)).parse()


ROBOT_SCENE = RobotScene(
    instances=[
        RobotInstance(
            identifier="robot_1",
            label="PR2 1",
            robot_type=PR2,
            pose=HomogeneousTransformationMatrix.from_xyz_rpy(1, 2.5, 0.0, yaw=0),
        ),
    ],
    active_identifier="robot_1",
)


def build_world(env_file: str, robot_xy: tuple[float, float]) -> World:
    """
    Build the environment and spawn its annotated robot.

    :param env_file: Environment URDF filename or absolute path.
    :param robot_xy: Robot starting x and y position in metres.
    :return: The assembled semantic world.
    """
    return ROBOT_SCENE.build_world(os.path.join(_WORLDS, env_file))


# whether the base may drive to help an arm reach (whole-body control). A plan
# built in the Plan Builder says where the robot stands, with its Navigate steps.
BASE_MAY_DRIVE_WHILE_REACHING = False

world = build_world(
    "/home/hassouna/cram-worktrees/cram-viz/coraplex/resources/worlds/apartment.urdf",
    (1, 2.5),
)
visualization = WorldVisualization.from_environment(
    world, default_backend=VisualizationBackend.CRAMERA
).start()

# --- objects placed in the Plan Builder ---
_obj0 = _parse_mesh("milk.stl")
_obj1 = _parse_mesh("bowl.stl")
with world.modify_world():
    world.merge_world_at_pose(
        _obj0,
        HomogeneousTransformationMatrix.from_xyz_rpy(
            1.12, 2.5, 1.9, roll=0, pitch=0, yaw=0, reference_frame=world.root
        ),
    )
    world.merge_world_at_pose(
        _obj1,
        HomogeneousTransformationMatrix.from_xyz_rpy(
            0.912, 2.581, 2.06, roll=0, pitch=0, yaw=0, reference_frame=world.root
        ),
    )
world.get_body_by_name("milk.stl").visual.shapes[0].color = Color(0.6, 0.63, 0.68)
world.get_body_by_name("bowl.stl").visual.shapes[0].color = Color(0.56, 0.84, 0.78)

robot = ROBOT_SCENE.selected_robot(world)
if isinstance(robot, HasMobileBase):
    robot.mobile_base.full_body_controlled = BASE_MAY_DRIVE_WHILE_REACHING
context = Context(
    world=world, robot=robot, _debug=False, ros_node=visualization.ros_node
)
with world.modify_world():
    WorldReasoner(world).reason()
    PlacementAnnotations(
        world,
        os.path.join(
            _WORLDS,
            "/home/hassouna/cram-worktrees/cram-viz/coraplex/resources/worlds/apartment.urdf",
        ),
    ).apply()
context.evaluate_conditions = False

plan = sequential(
    [
        ParkArmsAction(Arms.BOTH),
    ],
    context=context,
).plan
visualization.attach_plan(plan)

with simulated_robot_advanced:
    plan.perform()
