"""
Generated by the cramera Plan Builder — a RobotDemonstration subclass.
"""

import os
from dataclasses import dataclass

from coraplex.datastructures.dataclasses import Context
from coraplex.datastructures.enums import Arms, VisualizationBackend
from coraplex.datastructures.grasp import GraspDescription
from coraplex.demonstrations import RobotDemonstration
from coraplex.plans.factories import sequential
from coraplex.plans.plan import Plan
from coraplex.robot_plans.actions.composite.transporting import TransportAction
from coraplex.robot_plans.actions.core.navigation import NavigateAction
from coraplex.robot_plans.actions.core.pick_up import PickUpAction
from coraplex.robot_plans.actions.core.placing import PlaceAction
from coraplex.robot_plans.actions.core.robot_body import ParkArmsAction, MoveTorsoAction
from coraplex.view_manager import ViewManager
from semantic_digital_twin.api import (
    BodySpecification,
    Connection6DoFSpecification,
    RobotSpecification,
    WorldSpecification,
)
from semantic_digital_twin.datastructures.definitions import TorsoState
from semantic_digital_twin.reasoning.world_reasoner import WorldReasoner
from cramera.live.placement_annotations import PlacementAnnotations
from semantic_digital_twin.robots.robot_part_mixins import HasMobileBase
from semantic_digital_twin.robots.pr2 import PR2
from semantic_digital_twin.spatial_types import HomogeneousTransformationMatrix
from semantic_digital_twin.spatial_types.spatial_types import Pose
from semantic_digital_twin.world import World
from semantic_digital_twin.world_description.geometry import Color
from semantic_digital_twin.semantic_annotations.semantic_annotations import Table
from cramera.live.placement_surface import PlacementSurface
from krrood.entity_query_language.factories import a, variable

_HERE = os.path.dirname(__file__)
_WORLDS = os.path.join(_HERE, "..", "..", "resources", "worlds")
_OBJECTS = os.path.join(_HERE, "..", "..", "resources", "objects")

ENV_FILE = (
    "/home/hassouna/cram-worktrees/cram-viz/coraplex/resources/worlds/apartment.urdf"
)
ROBOT_XY = (1, 2.5)
# whether the base may drive to help an arm reach (whole-body control). A plan
# built in the Plan Builder says where the robot stands, with its Navigate steps.
BASE_MAY_DRIVE_WHILE_REACHING = False

# objects placed in the Plan Builder: (mesh, x, y, z, roll, pitch, yaw, (r, g, b))
OBJECTS = [
    ("milk.stl", 2.37, 2.1, 1.05, 0, 0, 0, (0.79, 0.63, 1)),
]


@dataclass(kw_only=True)
class CrameraPr2BuilderTransport20260921Demonstration(RobotDemonstration):
    """
    A demonstration composed in the cramera Plan Builder.
    """

    def build_simulated_world(self) -> World:
        """
        Build the selected environment with its annotated robot.

        :return: The assembled semantic world.
        """
        return WorldSpecification.from_urdf(
            os.path.join(_WORLDS, ENV_FILE),
            robots=[
                RobotSpecification(
                    semantic_annotation_type=self.used_robot,
                    world_T_odom=HomogeneousTransformationMatrix.from_xyz_rpy(
                        ROBOT_XY[0], ROBOT_XY[1], 0.0
                    ),
                ),
            ],
        ).to_domain_object()

    def is_scene_populated(self, world: World) -> bool:
        """
        Check whether every authored object exists in the world.

        :param world: World inspected for the authored objects.
        :return: Whether the scene already contains the complete object set.
        """
        return bool(OBJECTS) and all(
            len(world.get_bodies_by_name(spec[0])) == 1 for spec in OBJECTS
        )

    def populate_scene(self, world: World) -> None:
        """
        Spawn the authored objects at their saved poses.

        :param world: World receiving the movable object bodies.
        """
        # each object is free to move (Connection6DoF), so the robot can transport it
        for mesh, x, y, z, roll, pitch, yaw, rgb in OBJECTS:
            BodySpecification.mesh(
                mesh,
                os.path.join(_OBJECTS, mesh),
                color=Color(*rgb),
                parent_T_self=HomogeneousTransformationMatrix.from_xyz_rpy(
                    x, y, z, roll=roll, pitch=pitch, yaw=yaw
                ),
                connection_specification=Connection6DoFSpecification(),
            ).spawn(world)

    def build_context(self, world: World) -> Context:
        """
        Reason about the world and configure robot execution.

        :param world: Semantic world used for planning and execution.
        :return: Context for the selected robot.
        """
        with world.modify_world():
            WorldReasoner(world).reason()
            PlacementAnnotations(world, os.path.join(_WORLDS, ENV_FILE)).apply()
        robot = world.get_semantic_annotations_by_type(self.used_robot)[0]
        if isinstance(robot, HasMobileBase):
            robot.mobile_base.full_body_controlled = BASE_MAY_DRIVE_WHILE_REACHING
        context = Context(
            world=world, robot=robot, _debug=False, ros_node=self.ros_node
        )
        context.evaluate_conditions = False
        return context

    def build_plan(self, context: Context) -> Plan:
        """
        Compose the authored action sequence against the current world.

        :param context: Robot and world used to resolve the actions.
        :return: Executable plan containing the authored action sequence.
        """
        world = context.world  # bodies/poses below are resolved against it
        _target_s3 = PlacementSurface(
            world=world,
            body=world.get_body_by_name("milk.stl"),
            surface_type=Table,
            surface_name="apartment/table_area_main",
        )
        return sequential(
            [
                ParkArmsAction(Arms.BOTH),
                MoveTorsoAction(TorsoState.HIGH),
                TransportAction(
                    object_designator=world.get_body_by_name("milk.stl"),
                    target_location=_target_s3,
                    arm=Arms.LEFT,
                ),
            ],
            context=context,
        ).plan


def main() -> None:
    """
    Run the demonstration.

    RobotDemonstration.run() acquires the world, starts the visualization backend,
    attaches the plan and performs it. The backend defaults to CRAMERA (the browser
    viewer); CORAPLEX_VISUALIZATION overrides it, so `cramera-live` works unchanged and
    you can also force RVIZ / NONE from the outside.
    """
    CrameraPr2BuilderTransport20260921Demonstration(
        used_robot=PR2,
        collision_avoidance=True,
        default_visualization_backend=VisualizationBackend.CRAMERA,
    ).run()


if __name__ == "__main__":
    main()
