"""
The Garmi shuttling a labelled screw box between a shelf and a workbench.

Grown out of a Plan Builder demo: the carrying is spelled out as navigate / pick / place
rather than a TransportAction, because warehouse6 is a single hall mesh with no navigable
floor for a transport's costmap to search. Every base pose here is one captured in the
Plan Builder's 3D view.

The box keeps the size of ``milk.stl``, so poses captured for that one still fit; it is
generated by ``scripts/make_transport_box_mesh.py``.
"""

import os
from dataclasses import dataclass

from coraplex.datastructures.dataclasses import Context
from coraplex.datastructures.enums import Arms, VisualizationBackend
from coraplex.datastructures.grasp import GraspDescription
from coraplex.demonstrations import RobotDemonstration
from coraplex.plans.factories import sequential
from coraplex.plans.plan_node import PlanNode
from coraplex.robot_plans.actions.core.navigation import NavigateAction
from coraplex.robot_plans.actions.core.pick_up import PickUpAction
from coraplex.robot_plans.actions.core.placing import PlaceAction
from coraplex.robot_plans.actions.core.robot_body import ParkArmsAction, MoveTorsoAction
from coraplex.view_manager import ViewManager
from semantic_digital_twin.api import (
    BodySpecification,
    Connection6DoFSpecification,
    RobotSpecification,
    WorldSpecification,
)
from semantic_digital_twin.datastructures.definitions import TorsoState
from semantic_digital_twin.reasoning.world_reasoner import WorldReasoner
from semantic_digital_twin.robots.garmi import Garmi
from semantic_digital_twin.robots.robot_part_mixins import HasMobileBase
from semantic_digital_twin.spatial_types import HomogeneousTransformationMatrix
from semantic_digital_twin.spatial_types.spatial_types import Pose
from semantic_digital_twin.world import World
from semantic_digital_twin.world_description.world_entity import Body

_HERE = os.path.dirname(__file__)
_WORLDS = os.path.join(_HERE, "..", "..", "resources", "worlds")
_OBJECTS = os.path.join(_HERE, "..", "..", "resources", "objects")

ENV_FILE = "warehouse6.urdf"
ROBOT_XY = (1.5, 2.5)

BASE_MAY_DRIVE_WHILE_REACHING = False
"""
Whether the base may drive to help an arm reach (whole-body control).

Off, because every base pose in this plan is one that was captured deliberately: with it
on, a reach drives the base past the object and into the shelving.
"""

ROUND_TRIPS = 4
"""
How often the box travels to the workbench and back to the shelf.
"""

BOX_MESH = "screw_box.obj"
"""
The labelled cardboard box that is carried.
"""

CARRYING_ARM = Arms.LEFT
"""
The arm that picks and places, one hand throughout.
"""

ON_THE_SHELF = Pose.from_xyz_rpy(2.35, -0.05, 0.71)
"""
Where the box starts and is returned to.
"""

ON_THE_WORKBENCH = Pose.from_xyz_rpy(5.64, -0.93, 0.74, yaw=1.623)
"""
Where the box is delivered to.
"""

STANDING_AT_THE_SHELF = Pose.from_xyz_rpy(1.4, -0.29, 0.0)
"""
Base pose the robot reaches the shelf from.
"""

STANDING_AT_THE_WORKBENCH = Pose.from_xyz_rpy(5.73, -1.76, 0.0, yaw=1.55)
"""
Base pose the robot reaches the workbench from.
"""


@dataclass(kw_only=True)
class ScrewBoxShuttleDemonstration(RobotDemonstration):
    """
    Carries one labelled box back and forth between two stands.
    """

    def build_simulated_world(self) -> World:
        return WorldSpecification.from_urdf(
            os.path.join(_WORLDS, ENV_FILE),
            robots=[
                RobotSpecification(
                    semantic_annotation_type=self.used_robot,
                    world_T_odom=HomogeneousTransformationMatrix.from_xyz_rpy(
                        ROBOT_XY[0], ROBOT_XY[1], 0.0
                    ),
                ),
            ],
        ).to_domain_object()

    def is_scene_populated(self, world: World) -> bool:
        try:
            world.get_body_by_name(BOX_MESH)
        except Exception:
            return False
        return True

    def populate_scene(self, world: World) -> None:
        # free to move (Connection6DoF), so the robot can pick it up and carry it
        BodySpecification.mesh(
            BOX_MESH,
            os.path.join(_OBJECTS, BOX_MESH),
            parent_T_self=ON_THE_SHELF.to_homogeneous_matrix(),
            connection_specification=Connection6DoFSpecification(),
        ).spawn(world)

    def build_context(self, world: World) -> Context:
        with world.modify_world():
            WorldReasoner(world).reason()
        robot = world.get_semantic_annotations_by_type(self.used_robot)[0]
        if isinstance(robot, HasMobileBase):
            robot.mobile_base.full_body_controlled = BASE_MAY_DRIVE_WHILE_REACHING
        context = Context(
            world=world, robot=robot, _debug=False, ros_node=self.ros_node
        )
        context.evaluate_conditions = False
        return context

    def build_plan(self, context: Context) -> PlanNode:
        world = context.world  # bodies/poses below are resolved against it
        box = world.get_body_by_name(BOX_MESH)
        steps = []
        for _ in range(ROUND_TRIPS):
            steps.extend(
                self.carry(context, box, STANDING_AT_THE_SHELF, ON_THE_WORKBENCH)
            )
            steps.extend(
                self.carry(context, box, STANDING_AT_THE_WORKBENCH, ON_THE_SHELF)
            )
        return sequential(steps, context=context).plan

    def carry(
        self, context: Context, box: Body, stand: Pose, destination: Pose
    ) -> list:
        """
        One leg: fetch the box from where it stands and put it down at ``destination``.

        The robot drives to ``stand`` to take the box, and to the destination's own
        stand to put it down -- which is the other leg's ``stand``, so a leg ends where
        the next one begins.

        :param context: The plan context the actions are built against.
        :param box: The body being carried.
        :param stand: Base pose to pick the box up from.
        :param destination: Where the box is put down.
        """
        stand_to_place = (
            STANDING_AT_THE_WORKBENCH
            if destination is ON_THE_WORKBENCH
            else STANDING_AT_THE_SHELF
        )
        return [
            NavigateAction(self.against_world_root(context, stand)),
            ParkArmsAction(Arms.BOTH),
            MoveTorsoAction(TorsoState.MID),
            PickUpAction(box, CARRYING_ARM, self.grasp_for(context, box)),
            ParkArmsAction(Arms.BOTH),
            NavigateAction(self.against_world_root(context, stand_to_place)),
            PlaceAction(
                box, self.against_world_root(context, destination), CARRYING_ARM
            ),
            ParkArmsAction(Arms.BOTH),
        ]

    def grasp_for(self, context: Context, box: Body) -> GraspDescription:
        """
        How to take the box: the side to approach from is left to the robot's reach, so
        the box is grasped from a side the robot can stand on however it was put down.

        :param context: The plan context, for the robot's end effector.
        :param box: The body being grasped.
        """
        return GraspDescription.robot_relative_default(
            ViewManager.get_end_effector_view(CARRYING_ARM, context.robot),
            box.global_pose,
            box,
        )

    @staticmethod
    def against_world_root(context: Context, pose: Pose) -> Pose:
        """
        A pose from this file, expressed in the world it is used in.

        :param context: The plan context holding that world.
        :param pose: The pose to re-reference.
        """
        return Pose(
            pose.to_position(),
            pose.to_quaternion(),
            reference_frame=context.world.root,
        )


def main() -> None:
    """
    Run the demonstration.

    RobotDemonstration.run() acquires the world, starts the visualization backend,
    attaches the plan and performs it. The backend defaults to CRAMERA (the browser
    viewer); CORAPLEX_VISUALIZATION overrides it, so `cramera-live` works unchanged
    and you can also force RVIZ / NONE from the outside.
    """
    ScrewBoxShuttleDemonstration(
        used_robot=Garmi,
        collision_avoidance=False,
        default_visualization_backend=VisualizationBackend.CRAMERA,
    ).run()


if __name__ == "__main__":
    main()
