"""Generated by the cramera Plan Builder — a RobotDemonstration subclass."""
import os
from dataclasses import dataclass

from coraplex.datastructures.dataclasses import Context
from coraplex.datastructures.enums import Arms, VisualizationBackend
from coraplex.demonstrations import RobotDemonstration
from coraplex.plans.factories import sequential
from coraplex.plans.plan_node import PlanNode
from coraplex.robot_plans.actions.composite.transporting import TransportAction
from coraplex.robot_plans.actions.core.navigation import NavigateAction
from coraplex.robot_plans.actions.core.robot_body import ParkArmsAction, MoveTorsoAction
from semantic_digital_twin.api import (
    BodySpecification,
    Connection6DoFSpecification,
    RobotSpecification,
    WorldSpecification,
)
from semantic_digital_twin.datastructures.definitions import TorsoState
from semantic_digital_twin.reasoning.world_reasoner import WorldReasoner
from semantic_digital_twin.robots.pr2 import PR2
from semantic_digital_twin.spatial_types import HomogeneousTransformationMatrix
from semantic_digital_twin.spatial_types.spatial_types import Pose
from semantic_digital_twin.world import World
from semantic_digital_twin.world_description.geometry import Color
from semantic_digital_twin.semantic_annotations.semantic_annotations import CounterTop

_HERE = os.path.dirname(__file__)
_WORLDS = os.path.join(_HERE, "..", "..", "resources", "worlds")
_OBJECTS = os.path.join(_HERE, "..", "..", "resources", "objects")

ENV_FILE = "apartment.urdf"
ROBOT_XY = (1.5, 2.5)

# objects placed in the Plan Builder: (mesh, x, y, z, roll, pitch, yaw, (r, g, b))
OBJECTS = [
    ("milk.stl", 2.5, 2.3, 1, 0, 0, 0, (0.6, 0.63, 0.68)),
    ("bowl.stl", 2.4, 2, 1, 0, 0, 0, (0.56, 0.84, 0.78)),
    ("plate.stl", 2.9, 2.38, 0.95, 0, 0, 0, (0.79, 0.63, 1)),
]


@dataclass(kw_only=True)
class MyDemoDemonstration(RobotDemonstration):
    """A demonstration composed in the cramera Plan Builder."""

    def build_simulated_world(self) -> World:
        return WorldSpecification.from_urdf(
            os.path.join(_WORLDS, ENV_FILE),
            robots=[
                RobotSpecification(
                    semantic_annotation_type=self.used_robot,
                    world_T_odom=HomogeneousTransformationMatrix.from_xyz_rpy(
                        ROBOT_XY[0], ROBOT_XY[1], 0.0),
                ),
            ],
        ).to_domain_object()

    def is_scene_populated(self, world: World) -> bool:
        for spec in OBJECTS:
            try:
                world.get_body_by_name(spec[0])
            except Exception:
                return False
        return bool(OBJECTS)

    def populate_scene(self, world: World) -> None:
        # each object is free to move (Connection6DoF), so the robot can transport it
        for mesh, x, y, z, roll, pitch, yaw, rgb in OBJECTS:
            BodySpecification.mesh(
                mesh,
                os.path.join(_OBJECTS, mesh),
                color=Color(*rgb),
                parent_T_self=HomogeneousTransformationMatrix.from_xyz_rpy(
                    x, y, z, roll=roll, pitch=pitch, yaw=yaw),
                connection_specification=Connection6DoFSpecification(),
            ).spawn(world)

    def build_context(self, world: World) -> Context:
        with world.modify_world():
            WorldReasoner(world).reason()
        robot = world.get_semantic_annotations_by_type(self.used_robot)[0]
        context = Context(world=world, robot=robot, _debug=False, ros_node=self.ros_node)
        context.evaluate_conditions = False
        return context

    def build_plan(self, context: Context) -> PlanNode:
        world = context.world  # bodies/poses below are resolved against it
        # place "milk.stl" on a CounterTop — pose sampled by semantic_digital_twin
        _surfaces_s3 = world.get_semantic_annotations_by_type(CounterTop)
        if not _surfaces_s3:
            raise RuntimeError(
                "no CounterTop in this world for step 3 (transport milk.stl). "
                "This environment may not carry that annotation — "
                "see the Plan Builder's live /surfaces list for what is available."
            )
        _surface_s3 = _surfaces_s3[0]
        _pts_s3 = _surface_s3.sample_points_from_surface(
            body_to_sample_for=world.get_body_by_name("milk.stl"))
        if not _pts_s3:
            raise RuntimeError(
                "could not sample a free place pose on CounterTop for step 3 (transport milk.stl) "
                "(surface full or too small for milk.stl)."
            )
        _target_s3 = Pose(_pts_s3[0], reference_frame=_pts_s3[0].reference_frame)
        return sequential([
            ParkArmsAction(Arms.BOTH),
            MoveTorsoAction(TorsoState.HIGH),
            TransportAction(world.get_body_by_name("milk.stl"), _target_s3, Arms.LEFT),
        ], context=context).plan


def main() -> None:
    """Run the demonstration.

    RobotDemonstration.run() acquires the world, starts the visualization backend,
    attaches the plan and performs it. The backend defaults to CRAMERA (the browser
    viewer); CORAPLEX_VISUALIZATION overrides it, so `cramera-live` works unchanged
    and you can also force RVIZ / NONE from the outside.
    """
    MyDemoDemonstration(
        used_robot=PR2,
        default_visualization_backend=VisualizationBackend.CRAMERA,
    ).run()


if __name__ == "__main__":
    main()
