/* ============================================================================
 * panels/robot_scene/panel.js — the 3D scene panel.
 *
 * Renders whatever scenes/<scene>/scene.json describes — scene bundles are
 * generated by `cram-viz-onboard` from real coraplex demo runs. Also owns the
 * playback / live controls and the layers overlay.
 *
 * The three.js bootstrap, model/material loading, trajectory math and
 * pointer-drag handling live in sibling modules (scene-setup.js,
 * model-loader.js, playback.js, drag-controls.js, live-bridge.js) so this
 * file stays focused on scene-graph bookkeeping and wiring the viewer to the
 * rest of the page.
 *
 * Scene selection: ?scene=<name> URL parameter, else scenes/index.json default.
 *
 * Bus events:
 *   emits    scene:part-clicked {id}   click on a robot part / object
 *   emits    scene:step {step}         playback entered a plan step ('__done__' at end)
 *   emits    live:changed {on, url}    live bridge attached / detached
 *   listens  entity:highlight {ids}    glow the matching 3D objects
 *
 * window.RobotView stays exported for the console and split-resize.
 * ==========================================================================*/
Panels.define('robot-scene', function (root, bus) {
  const MATERIAL_UPGRADE_RETRY_DELAYS_MS = [1500, 4000, 9000, 13000];
  const FINALIZE_FALLBACK_MS = 15000;

  root.innerHTML =
    '<div class="panel-head">' +
    '  <h2>Robot · scene</h2>' +
    '  <select id="scene-select" style="display:none"></select>' +
    '</div>' +
    '<div class="stage">' +
    '  <div id="stage-bg" class="stage-bg"></div>' +
    '  <div id="viewer"></div>' +
    '  <div id="viewer-status" class="viewer-status">Loading scene…</div>' +
    '  <div id="layers-panel" class="layers-panel">' +
    '    <div class="lp-title">Layers</div>' +
    '    <label class="lp-row"><input type="checkbox" id="lyr-objects" checked><span>Bench objects</span></label>' +
    '    <label class="lp-row"><input type="checkbox" id="lyr-labels"><span>Object labels</span></label>' +
    '    <label class="lp-row"><input type="checkbox" id="lyr-floor" checked><span>Floor shadow</span></label>' +
    '    <div class="lp-legend" id="lp-legend"></div>' +
    '  </div>' +
    '  <div id="live-indicator" class="live-indicator">● LIVE</div>' +
    '  <div id="step-caption" class="step-caption hidden"></div>' +
    '  <div class="stage-hint">drag orbit · scroll zoom · right-drag pan · drag objects &amp; the blue place target</div>' +
    '</div>' +
    '<div class="workflow">' +
    '  <div class="workflow-head"><span class="wf-btns">' +
    '    <button id="live-btn" class="play-btn live" style="display:none" title="Attach to the running demo (cram-viz-live bridge) — renders the live world instead of the recording">◉ Live</button>' +
    '    <button id="play-btn" class="play-btn cram" title="Play the recorded coraplex + giskardpy motion trajectory">▶ Play robot motion</button>' +
    '  </span></div>' +
    '</div>';
  function $(id) { return root.querySelector('#' + id); }

  console.log('%c[cram_viz] robot-scene panel', 'color:#39d5c8;font-weight:bold');
  const container = $('viewer');
  const statusEl = $('viewer-status');
  const SCENES = 'scenes/';

  const Playback = window.RobotScenePlayback;
  const env = window.RobotSceneEnvironment.create(container);
  const scene3 = env.scene3, camera = env.camera, renderer = env.renderer, controls = env.controls;
  const worldRoot = env.worldRoot, ground = env.ground, floorTex = env.floorTex;

  const modelTamer = new window.RobotSceneModelLoader.ModelTamer(scene3);

  let needsRender = true;
  controls.addEventListener('change', function () { needsRender = true; });

  // ================================================================ scene ====
  let SCENE = null;              // scene.json payload
  let sceneBase = null;          // scenes/<name>/
  let traj = null;
  const models = [];             // {name, prefix, robot, obj}
  let robotModel = null;
  const objectMeshes = {};       // mesh key ('milk.stl') -> THREE.Group
  const objectLabels = {};       // mesh key -> label sprite
  const liveSpawned = {};        // mesh key -> true for objects added by live mode
  const objectPending = {};      // mesh key -> true while its geometry is loading
  let labelsOn = false;
  const objectIdByKey = {}, objectKeyById = {};
  const objLoader = new THREE.STLLoader(); // no manager: for live/on-demand loads
  const pendingTimeouts = [];

  // add one draggable object to the scene (bundle load or live spawn). spec:
  // {id, key, color, meshUrl?, format?  |  box:[x,y,z]}. Any mesh format the
  // vendored loaders support (stl/obj/dae) works; unknown → placeholder box.
  function addObject(spec) {
    // present, or its mesh is still in flight — the live reconcile runs at 15 Hz
    // and would otherwise re-request the same STL dozens of times before it lands
    if (objectMeshes[spec.key] || objectPending[spec.key]) return;
    objectPending[spec.key] = true;
    objectIdByKey[spec.key] = spec.id;
    objectKeyById[spec.id] = spec.key;
    const material = new THREE.MeshStandardMaterial({
      color: new THREE.Color(spec.color || '#cccccc'),
      roughness: 0.5, metalness: 0.05, envMapIntensity: 0.7,
    });
    function place(content) { // content: Mesh or Object3D
      content.traverse(function (c) {
        if (c.isMesh) {
          c.castShadow = true; c.receiveShadow = true;
          if (spec.tame && c.material && c.material.emissive) c.material.emissive.setRGB(0, 0, 0);
        }
      });
      const group = new THREE.Group();
      group.add(content);
      const box = new THREE.Box3().setFromObject(content);
      const top = isFinite(box.max.z) ? box.max.z : 0.15;
      const label = makeLabel(spec.id.replace(/_/g, ' '), spec.color);
      label.position.z = top + 0.09;
      label.visible = labelsOn;
      group.add(label);
      objectLabels[spec.key] = label;
      objectMeshes[spec.key] = group;
      delete objectPending[spec.key];
      worldRoot.add(group);
      needsRender = true;
    }
    function box(scale) {
      const s = scale || [0.06, 0.06, 0.1];
      place(new THREE.Mesh(new THREE.BoxGeometry(s[0], s[1], s[2]).translate(0, 0, s[2] / 2), material));
    }
    if (spec.box) { box(spec.box); return; }
    const format = (spec.format || (spec.meshUrl || '').split('?')[0].split('.').pop() || '').toLowerCase();
    if (format === 'obj' && THREE.OBJLoader) {
      new THREE.OBJLoader().load(spec.meshUrl, function (o) {
        o.traverse(function (c) { if (c.isMesh) c.material = material; });
        place(o);
      }, undefined, function () { box(); });
    } else if (format === 'dae' && THREE.ColladaLoader) {
      spec.tame = true; // dae carries its own (possibly glowing) materials
      new THREE.ColladaLoader().load(spec.meshUrl, function (c) { place(c.scene); },
        undefined, function () { box(); });
    } else {
      objLoader.load(spec.meshUrl, function (geometry) { place(new THREE.Mesh(geometry, material)); },
        undefined, function () { box(); });
    }
  }
  function removeObject(key) {
    const group = objectMeshes[key];
    if (!group) return;
    worldRoot.remove(group);
    group.traverse(function (c) {
      if (c.geometry) c.geometry.dispose();
      if (c.material) { c.material.map && c.material.map.dispose(); c.material.dispose(); }
    });
    delete objectMeshes[key]; delete objectLabels[key];
    delete objectIdByKey[key]; delete liveSpawned[key]; delete objectPending[key];
  }

  // canvas-sprite name tag, colour-dotted to match the object
  function makeLabel(text, color) {
    const pad = 16, fontSize = 34, dot = 22;
    const canvas = document.createElement('canvas');
    let context = canvas.getContext('2d');
    context.font = '600 ' + fontSize + 'px Inter, sans-serif';
    canvas.width = context.measureText(text).width + pad * 2 + dot + 10;
    canvas.height = fontSize + pad * 2;
    context = canvas.getContext('2d');
    context.font = '600 ' + fontSize + 'px Inter, sans-serif';
    context.fillStyle = 'rgba(10,17,32,0.82)';
    const r = 12, w = canvas.width, h = canvas.height;
    context.beginPath();
    context.moveTo(r, 0); context.arcTo(w, 0, w, h, r); context.arcTo(w, h, 0, h, r);
    context.arcTo(0, h, 0, 0, r); context.arcTo(0, 0, w, 0, r); context.closePath();
    context.fill();
    context.strokeStyle = 'rgba(57,213,200,0.5)'; context.lineWidth = 2; context.stroke();
    context.fillStyle = color || '#39d5c8';
    context.beginPath(); context.arc(pad + dot / 2, h / 2, dot / 2, 0, Math.PI * 2); context.fill();
    context.fillStyle = '#e8eefb'; context.textBaseline = 'middle';
    context.fillText(text, pad + dot + 10, h / 2);
    const tex = new THREE.CanvasTexture(canvas);
    tex.anisotropy = 4;
    const sprite = new THREE.Sprite(new THREE.SpriteMaterial({ map: tex, transparent: true, depthTest: false }));
    const s = 0.0016;
    sprite.scale.set(canvas.width * s, canvas.height * s, 1);
    return sprite;
  }
  let linkToPart = {};           // link name -> part name (from robot.parts)
  const readyCbs = [];
  let finalized = false;

  const manager = new THREE.LoadingManager();
  function makeUrdfLoader() { return window.RobotSceneModelLoader.makeUrdfLoader(manager); }

  function sceneNameFromUrl() {
    const m = /[?&]scene=([\w-]+)/.exec(window.location.search);
    return m ? m[1] : null;
  }

  fetch(SCENES + 'index.json')
    .then(function (r) { return r.ok ? r.json() : { default: null, scenes: [] }; })
    .catch(function () { return { default: null, scenes: [] }; })
    .then(function (index) {
      const name = sceneNameFromUrl() || index.default;
      // header dropdown: switch between all onboarded scenes
      const sel = $('scene-select');
      if (sel && index.scenes && index.scenes.length > 1) {
        sel.innerHTML = index.scenes.map(function (s) {
          return '<option value="' + s + '"' + (s === name ? ' selected' : '') + '>' + s + '</option>';
        }).join('');
        sel.style.display = '';
        sel.addEventListener('change', function () {
          window.location.search = '?scene=' + encodeURIComponent(sel.value);
        });
      }
      if (!name) {
        if (statusEl) statusEl.textContent = 'No scene found — run tools/onboard_demo.py first.';
        return;
      }
      sceneBase = SCENES + name + '/';
      return fetch(sceneBase + 'scene.json').then(function (r) { return r.json(); }).then(loadScene);
    })
    .catch(function (e) {
      if (statusEl) statusEl.textContent = 'Scene failed to load: ' + e;
    });

  function loadScene(sc) {
    SCENE = sc;
    if (statusEl) statusEl.textContent = 'Loading ' + sc.name + '…';
    // robot part lookup (link -> part name)
    linkToPart = {};
    const parts = (sc.robot && sc.robot.parts) || {};
    for (const part in parts) parts[part].forEach(function (l) { linkToPart[l] = part; });

    sc.models.forEach(function (m) {
      makeUrdfLoader().load(sceneBase + m.urdf, function (obj) {
        const entry = { name: m.name, prefix: m.prefix || '', robot: !!m.robot, obj: obj };
        models.push(entry);
        if (m.robot) robotModel = entry;
        worldRoot.add(obj);
        needsRender = true;
      });
    });

    (sc.objects || []).forEach(function (o) {
      addObject({ id: o.id, key: o.key, meshUrl: sceneBase + o.mesh, color: o.color });
    });

    buildMarker(sc.placeTarget);
    manager.onLoad = function () {
      modelTamer.upgrade(models);
      if (!finalized) finalize();
      needsRender = true;
    };
    MATERIAL_UPGRADE_RETRY_DELAYS_MS.forEach(function (ms) {
      pendingTimeouts.push(setTimeout(function () {
        if (models.length) { modelTamer.upgrade(models); dropGroundToScene(); needsRender = true; }
      }, ms));
    });
    // a scene with zero models would otherwise never finalize (nothing to
    // wait on), so this fallback isn't gated on models.length
    pendingTimeouts.push(setTimeout(function () { finalize(); }, FINALIZE_FALLBACK_MS));
  }

  function finalize() {
    if (finalized) return;
    finalized = true;
    modelTamer.upgrade(models);
    dropGroundToScene();
    fetch(sceneBase + (SCENE.trajectory || 'trajectory.json'))
      .then(function (r) { return r.ok ? r.json() : null; })
      .then(function (d) {
        traj = d;
        setupTransports();
        if (traj) applyFrame(0);
        frameCamera();
        if (statusEl) statusEl.classList.add('hidden');
        readyCbs.forEach(function (cb) { cb(); });
        needsRender = true;
      }).catch(function () {
        frameCamera();
        if (statusEl) statusEl.classList.add('hidden');
        readyCbs.forEach(function (cb) { cb(); });
      });
  }

  function dropGroundToScene() {
    const envs = models.filter(function (m) { return !m.robot; });
    if (!envs.length) return;
    const box = new THREE.Box3();
    envs.forEach(function (m) { box.expandByObject(m.obj); });
    if (!isFinite(box.min.y) || !isFinite(box.min.x)) return;
    const w = (box.max.x - box.min.x) + 0.4;
    const d = (box.max.z - box.min.z) + 0.4;
    ground.geometry.dispose();
    ground.geometry = new THREE.PlaneGeometry(w, d);
    ground.position.set((box.min.x + box.max.x) / 2, box.min.y + 0.002, (box.min.z + box.max.z) / 2);
    floorTex.repeat.set(w / 0.6, d / 0.6);
    floorTex.needsUpdate = true;
    needsRender = true;
  }

  // ---- playback ----------------------------------------------------------------
  let playing = false, playhead = 0, stepCb = function () {};
  let lastStep = null;
  const transportBlender = new Playback.TransportBlender();

  function applyFrame(f) {
    if (!traj) return;
    const F = traj.frames, i0 = Math.floor(f), i1 = Math.min(i0 + 1, F.length - 1), t = f - i0;
    const f0 = F[i0], f1 = F[i1];
    for (const key in f0) {
      const joint = Playback.resolveJoint(models, key);
      if (joint) joint.setJointValue(f0[key] + ((f1[key] !== undefined ? f1[key] : f0[key]) - f0[key]) * t);
    }
    if (robotModel && traj.base && traj.base[i0]) {
      Playback.setPose(robotModel.obj, traj.base[i0], traj.base[i1] || traj.base[i0], t);
      const baseOffset = transportBlender.baseOffsetAt(f);
      robotModel.obj.position.x += baseOffset.x; robotModel.obj.position.y += baseOffset.y;
    }
    if (traj.objects) {
      const o0 = traj.objects[i0], o1 = traj.objects[i1];
      for (const name in objectMeshes) {
        if (o0[name] && o1[name]) {
          Playback.setPose(objectMeshes[name], o0[name], o1[name], t);
          const objectOffset = transportBlender.objOffsetAt(name, f);
          objectMeshes[name].position.x += objectOffset.x;
          objectMeshes[name].position.y += objectOffset.y;
          // while the object is still resting (before its pick), hold the
          // dragged surface height so it doesn't float / clip
          const pickDelta = transportBlender.pickDelta(name);
          if (pickDelta.zAbs != null && transportBlender.restingBeforePick(name, f)) {
            objectMeshes[name].position.z = pickDelta.zAbs;
          }
        }
      }
    }
    if (SCENE && SCENE.segments) {
      const seg = SCENE.segments.find(function (s) { return i0 >= s.start && i0 < s.end; });
      if (seg && seg.step !== lastStep) { lastStep = seg.step; stepCb(seg.step); }
    }
  }

  function playTrajectory() {
    if (!traj) return false;
    playing = true; playhead = 0; lastStep = null;
    return true;
  }
  function stopTrajectory() { playing = false; }

  // ---- adjustable pick spawns + place target ----------------------------------
  // The scene records for each manipulation segment which object moves and its
  // attach/detach frames — no detection heuristics needed here.
  const placeDelta = { x: 0, y: 0 };
  let PLACE0 = null;

  function setupTransports() {
    transportBlender.configure(SCENE && SCENE.objects, SCENE && SCENE.segments, objectKeyById);
  }

  // ---- camera ------------------------------------------------------------------
  let follow = true;
  const _target = new THREE.Vector3(), _base = new THREE.Vector3();
  function frameCamera() {
    if (!robotModel) return;
    const box = new THREE.Box3().setFromObject(robotModel.obj);
    const c = box.getCenter(new THREE.Vector3());
    controls.target.copy(c);
    camera.position.set(c.x + 3.2, c.y + 1.6, c.z + 3.4);
    controls.update();
    needsRender = true;
  }
  function robotCenter(out) {
    if (!robotModel) return false;
    robotModel.obj.getWorldPosition(_base);
    out.copy(_base); out.y += 0.6;
    return true;
  }

  // ---- place-target marker (blue corner brackets) -------------------------------
  const marker = new THREE.Group();
  let MARKER_LIMIT = null;
  function buildMarker(pt) {
    if (!pt) { marker.visible = false; return; }
    const blue = 0x35a7ff;
    const barMat = new THREE.MeshBasicMaterial({ color: blue });
    const hx = 0.30, hy = 0.22, L = 0.14, W = 0.022, H = 0.012;
    [[-1, -1], [1, -1], [-1, 1], [1, 1]].forEach(function (c) {
      const armX = new THREE.Mesh(new THREE.BoxGeometry(L, W, H), barMat);
      armX.position.set(c[0] * (hx - L / 2), c[1] * hy, 0);
      const armY = new THREE.Mesh(new THREE.BoxGeometry(W, L, H), barMat);
      armY.position.set(c[0] * hx, c[1] * (hy - L / 2), 0);
      marker.add(armX, armY);
    });
    const fill = new THREE.Mesh(
      new THREE.PlaneGeometry(hx * 2, hy * 2),
      new THREE.MeshBasicMaterial({ color: blue, transparent: true, opacity: 0.08, depthWrite: false })
    );
    marker.add(fill);
    PLACE0 = { x: pt.pos[0], y: pt.pos[1] };
    MARKER_LIMIT = pt.bounds;
    marker.position.set(PLACE0.x, PLACE0.y, pt.z);
    marker.visible = true; // independent of the "Bench objects" layer toggle
    worldRoot.add(marker);
  }

  // ---- drag + click-to-inspect: object/marker dragging lives in drag-controls;
  // this panel only supplies the scene-specific hit tests + bookkeeping ----------
  function objLimit() {
    return (SCENE && SCENE.dragBounds) || { minX: -50, maxX: 50, minY: -50, maxY: 50 };
  }
  const envMeshesCache = { list: null };
  function envMeshes() {
    if (envMeshesCache.list) return envMeshesCache.list;
    const list = [];
    models.forEach(function (m) {
      if (m.robot) return;
      m.obj.traverse(function (c) { if (c.isMesh) list.push(c); });
    });
    if (ground) list.push(ground);
    envMeshesCache.list = list;
    return list;
  }

  function classifyRobotClick(dragRay) {
    if (!robotModel) return null;
    const hits = dragRay.intersectObject(robotModel.obj, true);
    for (let i = 0; i < hits.length; i++) {
      let o = hits[i].object;
      while (o && o !== scene3) {
        if (o.isURDFLink && o.name) {
          return linkToPart[String(o.name)] || (SCENE.robot && SCENE.robot.name) || null;
        }
        o = o.parent;
      }
    }
    return null;
  }

  const dragControls = new window.RobotSceneDragControls.DragControls({
    camera: camera, renderer: renderer, worldRoot: worldRoot,
    getObjectMeshes: function () { return objectMeshes; },
    getObjectGroup: function (key) { return objectMeshes[key]; },
    getMarker: function () { return { group: marker, visible: marker.visible !== false }; },
    getEnvMeshes: envMeshes,
    getDragBounds: objLimit,
    getMarkerBounds: function () { return MARKER_LIMIT; },
    isLive: function () { return liveBridge.isOn(); },
    isPlaying: function () { return playing; },
    objectIdFor: function (key) { return objectIdByKey[key] || null; },
    classifyMiss: function (e) {
      const rect = renderer.domElement.getBoundingClientRect();
      const ndc = new THREE.Vector2(
        ((e.clientX - rect.left) / rect.width) * 2 - 1,
        -((e.clientY - rect.top) / rect.height) * 2 + 1
      );
      const ray = new THREE.Raycaster();
      ray.setFromCamera(ndc, camera);
      return classifyRobotClick(ray);
    },
    controlsEnabled: function (on) { controls.enabled = on; },
    onObjectDragStart: function () {},
    onObjectDrag: function (key, x, y, z) {
      if (liveBridge.isOn()) {
        liveDraggedKey = key;
        liveBridge.postMove(key, x, y, z, false);
      } else {
        transportBlender.recordDrag(key, x, y, z);
        if (traj) applyFrame(playhead);
      }
      needsRender = true;
    },
    onObjectDragEnd: function (key, x, y, z) {
      if (liveBridge.isOn()) liveBridge.postMove(key, x, y, z, true);
      liveDraggedKey = null;
      needsRender = true;
    },
    onMarkerDrag: function (x, y) {
      placeDelta.x = x - PLACE0.x; placeDelta.y = y - PLACE0.y;
      transportBlender.setPlaceDelta(placeDelta.x, placeDelta.y);
      needsRender = true;
    },
    onClick: function (id) { if (partClickCb) partClickCb(id); },
  });
  let partClickCb = null;

  // glow entities in 3D — accepts object ids, mesh keys or segment step names
  function highlightObjects(ids) {
    const set = {};
    (ids || []).forEach(function (id) {
      id = String(id);
      set[id] = 1;
      if (SCENE && SCENE.segments) {
        const seg = SCENE.segments.find(function (s) { return s.step === id; });
        if (seg && seg.picks) set[seg.picks] = 1;
      }
    });
    for (const key in objectMeshes) {
      const on = !!set[key] || !!set[objectIdByKey[key]];
      objectMeshes[key].traverse(function (c) {
        if (c.isMesh && c.material && c.material.emissive) {
          c.material.emissive.setHex(on ? 0x39d5c8 : 0x000000);
          c.material.emissiveIntensity = on ? 0.55 : 0;
        }
      });
    }
    // direct link references: KB joint entities (l_shoulder_pan_joint → its
    // child link) and URDF-tree nodes ('urdf:<link>') resolve to link names
    const linkSet = {};
    (ids || []).forEach(function (id) {
      id = String(id);
      if (id.indexOf('urdf:') === 0) linkSet[id.slice(5)] = 1;
      const j = robotModel && robotModel.obj.joints && robotModel.obj.joints[id];
      if (j) {
        for (let i = 0; i < j.children.length; i++) {
          if (j.children[i].isURDFLink) { linkSet[j.children[i].name] = 1; break; }
        }
      }
    });
    // robot: glow meshes by part (scene.robot.parts, e.g. PR2LeftArm), by link,
    // or the whole robot when its own id is selected
    if (robotModel) {
      const robotName = SCENE && SCENE.robot && SCENE.robot.name;
      const wholeRobot = !!(robotName && set[robotName]);
      robotModel.obj.traverse(function (c) {
        if (!c.isMesh) return;
        const link = linkNameOfMesh(c);
        const part = linkToPart[link];
        const on = wholeRobot || !!(part && set[part]) || !!linkSet[link];
        const mats = Array.isArray(c.material) ? c.material : [c.material];
        mats.forEach(function (m) {
          if (m && m.emissive) {
            m.emissive.setHex(on ? 0x39d5c8 : 0x000000);
            m.emissiveIntensity = on ? 0.45 : 0;
          }
        });
      });
    }
    // the place area: brighten the blue corner marker
    if (PLACE0) {
      const on = !!set['place_area'];
      marker.traverse(function (c) {
        if (!c.isMesh) return;
        c.material.color.setHex(on ? 0x8fdcff : 0x35a7ff);
        if (c.material.transparent) c.material.opacity = on ? 0.26 : 0.08;
      });
    }
    needsRender = true;
  }
  // ModelTamer keeps linkNameOf private; walk the URDF-link ancestry here too
  // for highlighting (same lookup, independent concern from material taming).
  function linkNameOfMesh(c) {
    let o = c;
    while (o) { if (o.isURDFLink && o.name) return String(o.name); o = o.parent; }
    return '';
  }

  // ---- LIVE mode: attach to a running demo (live_viz bridge, RViz-style) -----
  // the live-bridge module streams the executing world's joints/base/objects
  // in the exact trajectory frame format; while attached, the viewer renders
  // those instead of the recording. The button appears whenever a bridge responds.
  const liveBtn = $('live-btn');
  const liveDot = $('live-indicator');
  const liveCbs = [];              // notified on attach/detach (graph tabs)
  let liveDraggedKey = null;       // object being dragged (poll must not fight it)
  let liveStateKeys = {};          // objects present in the newest /state payload
  let liveSyncing = false;

  const liveBridge = new window.RobotSceneLiveBridge.LiveBridge({
    onProbeResult: function (available) { if (liveBtn && !liveBridge.isOn()) liveBtn.style.display = available ? '' : 'none'; },
    onFrame: applyLive,
    onReconcileTick: syncLiveObjects,
    onAttach: function () { setLiveUi(true); },
    onDetach: function () { setLiveUi(false); },
  });

  function applyLive(st) {
    if (!st || !st.frames) return;
    for (const key in st.frames) {
      const joint = Playback.resolveJoint(models, key);
      if (joint) joint.setJointValue(st.frames[key]);
    }
    if (robotModel && st.base) Playback.setPose(robotModel.obj, st.base, st.base, 0);
    let unknown = false;
    liveStateKeys = st.objects || {};
    for (const key in liveStateKeys) {
      if (key === liveDraggedKey) continue; // the mouse owns this one right now
      const group = objectMeshes[key];
      if (group) {
        // the running world HAS this object, so it belongs on screen. An earlier
        // catalog answer may have hidden it (the demo spawns its objects some
        // seconds after the world exists — attaching before that used to hide
        // every bundle object permanently, because a hidden-but-known object
        // never counts as "unknown" and so never triggered another reconcile).
        if (!group.visible) { group.visible = true; needsRender = true; }
        Playback.setPose(group, liveStateKeys[key], liveStateKeys[key], 0);
      } else unknown = true; // an object the demo spawned mid-run
    }
    if (unknown) syncLiveObjects(); // fetch the catalog & spawn the newcomers
    if (follow && robotCenter(_target)) controls.target.lerp(_target, 0.08);
    needsRender = true;
  }

  // sync the scene's objects to the ones that actually exist in the running
  // world: spawn any the viewer is missing (geometry served by the bridge),
  // hide bundle objects the demo doesn't have. Runs once per attach.
  function syncLiveObjects() {
    if (!liveBridge.isOn() || liveSyncing) return;
    liveSyncing = true;
    liveBridge.fetchObjects()
      .then(function (d) {
        const live = d.objects || [];
        const liveKeys = {};
        live.forEach(function (o) {
          liveKeys[o.key] = 1;
          if (objectMeshes[o.key]) { // already present — reuse
            objectMeshes[o.key].visible = true;
            return;
          }
          const spec = { id: o.id, key: o.key, color: o.color };
          if (o.kind === 'mesh' && o.mesh) { spec.meshUrl = liveBridge.url() + o.mesh; spec.format = o.format; }
          else spec.box = o.size || [0.06, 0.06, 0.1];
          liveSpawned[o.key] = true;
          addObject(spec);
        });
        // Hide (don't delete) bundle objects the live world doesn't have — but
        // only once the bridge actually reports objects. An empty catalog means
        // "the demo hasn't spawned them yet" (or the world was mid-modification
        // when the bridge last bound), not "this world has no objects"; hiding
        // on that answer blanks the scene for the rest of the session.
        if (live.length || Object.keys(liveStateKeys).length) {
          for (const key in objectMeshes) {
            if (!liveKeys[key] && !(key in liveStateKeys)) objectMeshes[key].visible = false;
          }
        }
        needsRender = true;
      }).catch(function () {})
      .then(function () { liveSyncing = false; });
  }

  function setLiveUi(on) {
    liveCbs.forEach(function (cb) { try { cb(on); } catch (e) {} });
    if (liveDot) liveDot.classList.toggle('on', on);
    if (liveBtn) {
      liveBtn.classList.toggle('on', on);
      liveBtn.textContent = on ? '◉ LIVE — attached' : '◉ Live';
    }
    if (on) {
      playing = false;
      liveStateKeys = {};
      syncLiveObjects();
    } else {
      // remove objects that only existed for the live world, restore the rest
      for (const key in liveSpawned) removeObject(key);
      for (const key in objectMeshes) objectMeshes[key].visible = true;
      if (traj) applyFrame(playhead); // back to the recording
    }
    needsRender = true;
  }
  function setLive(on) { if (on) liveBridge.attach(); else liveBridge.detach(); }
  if (liveBtn) liveBtn.addEventListener('click', function () { setLive(!liveBridge.isOn()); });
  liveBridge.startProbing();

  // ---- render loop -----------------------------------------------------------------
  let running = true;
  function tick() {
    if (!running) return;
    requestAnimationFrame(tick);
    const moved = controls.update();
    if (playing && traj && !liveBridge.isOn()) {
      playhead += ((traj.fps || 30) / 60) * 1.6;
      if (playhead >= traj.frames.length - 1) { playhead = traj.frames.length - 1; playing = false; stepCb('__done__'); }
      applyFrame(playhead);
      if (follow && robotCenter(_target)) controls.target.lerp(_target, 0.06);
      needsRender = true;
    }
    if (!needsRender && !moved && !controls.autoRotate) return;
    env.renderFrame();
    needsRender = false;
  }
  tick();
  env.resize();

  window.RobotView = {
    onReady: function (cb) { if (finalized && traj) cb(); else readyCbs.push(cb); },
    hasTrajectory: function () { return !!traj; },
    playTrajectory: playTrajectory,
    stopTrajectory: stopTrajectory,
    isPlayingTrajectory: function () { return playing; },
    onStepStart: function (cb) { stepCb = cb; },
    setAutoRotate: function (on) { controls.autoRotate = on; controls.autoRotateSpeed = 0.5; needsRender = true; },
    setFloorVisible: function (on) { ground.visible = on; needsRender = true; },
    setFollow: function (on) { follow = on; },
    setPropsVisible: function (on) {
      for (const n in objectMeshes) objectMeshes[n].visible = on;
      needsRender = true;
    },
    highlightObjects: highlightObjects,
    onPartClick: function (cb) { partClickCb = cb; },
    getScene: function () { return SCENE; },
    // live bridge, shared with the graph panel (plan / statechart tabs)
    isLive: function () { return liveBridge.isOn(); },
    liveUrl: function () { return liveBridge.url(); },
    onLiveChange: function (cb) { liveCbs.push(cb); },
    setLabelsAlways: function (on) {
      labelsOn = !!on;
      for (const k in objectLabels) objectLabels[k].visible = labelsOn;
      needsRender = true;
    },
  };

  // ==================================================== panel wiring =========
  // Everything below couples the viewer to the page: buttons, overlays and the
  // event bus. The 3D code above knows nothing about other panels.
  const RobotView = window.RobotView;

  // ---- bus: outbound ---------------------------------------------------------
  RobotView.onPartClick(function (id) { bus.emit('scene:part-clicked', { id: id }); });
  RobotView.onLiveChange(function (on) { bus.emit('live:changed', { on: on, url: RobotView.liveUrl() }); });

  // ---- bus: inbound ----------------------------------------------------------
  bus.on('entity:highlight', function (p) { highlightObjects((p && p.ids) || []); });

  // ---- play button -----------------------------------------------------------
  const playBtn = $('play-btn');
  playBtn.addEventListener('click', function () {
    if (!RobotView.hasTrajectory()) return;
    if (RobotView.isPlayingTrajectory()) {
      RobotView.stopTrajectory();
      playBtn.classList.remove('playing'); playBtn.textContent = '▶ Play robot motion';
    } else {
      RobotView.playTrajectory();
      playBtn.classList.add('playing'); playBtn.textContent = '⏸ Stop';
    }
  });
  RobotView.onStepStart(function (step) {
    if (step === '__done__') {
      playBtn.classList.remove('playing'); playBtn.textContent = '▶ Play robot motion';
      highlightObjects([]);
    }
    bus.emit('scene:step', { step: step });
  });

  // ---- layers panel ----------------------------------------------------------
  function bindLayer(id, method) {
    const el = $(id);
    el.addEventListener('change', function () { RobotView[method](el.checked); });
  }
  bindLayer('lyr-objects', 'setPropsVisible');
  bindLayer('lyr-labels', 'setLabelsAlways');
  bindLayer('lyr-floor', 'setFloorVisible');
  RobotView.onReady(function () {
    const leg = $('lp-legend');
    const sc = RobotView.getScene();
    if (!leg || !sc || !sc.objects) return;
    leg.innerHTML = sc.objects.map(function (o) {
      return '<div class="li"><span class="dot" style="background:' + o.color + '"></span>' +
        o.id.replace(/_/g, ' ').replace(/[&<>]/g, '') + '</div>';
    }).join('');
  });

  // ---- teardown ---------------------------------------------------------------
  return {
    destroy: function () {
      running = false;
      pendingTimeouts.forEach(clearTimeout);
      liveBridge.destroy();
      dragControls.destroy();
      env.dispose();
    },
  };
});
