'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const context = {window: {}, RangeError};
vm.runInNewContext(fs.readFileSync(path.join(__dirname, '../../../cramera/src/cramera/web/core/builder_state.js'), 'utf8'), context, {filename: path.join(__dirname, '../../../cramera/src/cramera/web/core/builder_state.js')});
const State = context.window.PlanBuilderState;
const mobile = {name: 'PR2', steps: ['navigate', 'park_arms'], arms: ['LEFT', 'RIGHT', 'BOTH']};
const fixed = {name: 'Tracy', steps: ['park_arms'], arms: ['BOTH']};
const state = new State([mobile, fixed]);
const first = state.addRobot(mobile.name, {x: 1, y: 2, yaw: 0});
const second = state.addRobot(mobile.name, {x: 4, y: 2, yaw: Math.PI / 2});
assert.notEqual(first.id, second.id);
assert.equal(state.instances.length, 2);
assert.equal(state.activeRobot(), second);
assert.equal(first.model, mobile.name);
assert.equal(second.label, 'PR2 2');
assert.equal(second.yaw, Math.PI / 2);
const firstSteps = [{type: 'navigate', params: {x: 6}}];
state.selectInstance(first.id, []);
state.selectInstance(second.id, firstSteps);
assert.equal(state.activeRobot(), second);
assert.deepEqual(state.selectInstance(first.id, []).steps, firstSteps);
state.updateRobot(first.id, {label: 'Courier', x: 8, yaw: -Math.PI / 2});
assert.equal(first.label, 'Courier');
assert.equal(first.x, 8);
assert.equal(first.y, 2);
assert.equal(first.yaw, -Math.PI / 2);
state.updateRobot(first.id, {model: fixed.name});
assert.equal(first.model, fixed.name);
assert.deepEqual(Array.from(first.steps), []);
state.updateRobot(first.id, {label: '   '});
assert.equal(first.label, fixed.name);
assert.throws(() => state.addRobot('unknown'), RangeError);
assert.throws(() => state.selectInstance('missing', []), RangeError);
assert.throws(() => state.updateRobot(first.id, {x: NaN}), RangeError);
assert.throws(() => state.updateRobot(first.id, {model: 'unknown'}), RangeError);
assert.equal(state.removeRobot(second.id).id, first.id);
assert.equal(state.removeRobot(first.id), null);
assert.equal(state.instances.length, 1);
const third = state.addRobot(fixed.name);
assert.notEqual(third.id, second.id);
assert.equal(third.x, State.initialRobotPosition().x);
assert.equal(third.y, State.initialRobotPosition().y);
assert.equal(third.yaw, 0);
state.removeRobot(third.id);
assert.equal(state.activeRobot(), first);
console.log('Robot instances keep independent identities, poses, plans, and capability-aware selections.');
