'use strict';
const assert = require('assert');
const fs = require('fs');
const path = require('path');
const vm = require('vm');
const context = {window: {}};
vm.runInNewContext(fs.readFileSync(path.join(__dirname, '../../../cramera/src/cramera/web/core/builder_state.js'), 'utf8'), context);
const State = context.window.PlanBuilderState;
const initialPosition = State.initialRobotPosition();
const authoredPosition = State.initialRobotPosition();
authoredPosition.x += 1;
assert.notStrictEqual(authoredPosition.x, initialPosition.x);
assert.strictEqual(State.initialRobotPosition().x, initialPosition.x);
const mobile = {name: 'mobile', steps: ['navigate', 'pick'], arms: ['LEFT', 'RIGHT', 'BOTH']};
const fixed = {name: 'fixed', steps: ['pick'], arms: ['BOTH']};
const state = new State([mobile, fixed]);
assert.strictEqual(state.robot('mobile'), mobile);
assert.strictEqual(state.robot('unknown'), null);
const navigate = {type: 'navigate', params: {x: 4}};
const pick = {type: 'pick', params: {object: 'milk.stl', arm: 'LEFT'}};
const adapted = state.adaptSteps([navigate, pick], 'fixed');
assert.strictEqual(adapted.length, 1);
assert.strictEqual(adapted[0].params.arm, 'BOTH');
assert.strictEqual(adapted[0].params.object, pick.params.object);
assert.strictEqual(pick.params.arm, 'LEFT');
assert.deepStrictEqual(JSON.parse(JSON.stringify(state.adaptSteps([navigate, pick], 'mobile'))), [navigate, pick]);
const objects = [{mesh: 'milk.stl', x: 0, y: 0, z: 0}, {mesh: 'bowl.stl', x: 9}];
state.capture(objects, {'milk.stl': [1.23456, 2.5, 0.85, 0, 0, Math.SQRT1_2, Math.SQRT1_2]});
assert.strictEqual(objects[0].x, 1.23456);
assert.strictEqual(objects[0].y, 2.5);
assert.strictEqual(objects[0].z, 0.85);
assert(Math.abs(objects[0].yaw - Math.PI / 2) < 1e-12);
assert.strictEqual(objects[0].roll, 0);
assert.strictEqual(objects[0].pitch, 0);
assert.strictEqual(objects[1].x, 9);
state.capture(objects, {'milk.stl': [1, NaN, 2, 0, 0, 0, 1]});
assert.strictEqual(objects[0].x, 1.23456);
state.capture(objects, {'milk.stl': [1, 2]});
assert.strictEqual(objects[0].x, 1.23456);
console.log('builder state: capability pruning, default arms, captured poses passed');
assert.strictEqual(state.adaptSteps([pick], 'unknown').length, 0);
const dataset = path.join(__dirname, '..', 'dataset');
assert.strictEqual(state.recordFailure('mobile', fs.readFileSync(path.join(dataset, 'missing_robot_dependency.log'), 'utf8')), 'Missing ROS package: ur_robot_driver. Install the robot description dependencies, then retry.');
assert.strictEqual(state.failure('mobile'), 'Missing ROS package: ur_robot_driver. Install the robot description dependencies, then retry.');
assert.strictEqual(state.recordFailure('fixed', fs.readFileSync(path.join(dataset, 'robot_annotation_mismatch.log'), 'utf8')), 'Robot model does not match its annotation: missing left_fr3_link8.');
assert.strictEqual(state.failure('unknown'), '');
state.clearFailure('mobile');
assert.strictEqual(state.failure('mobile'), '');
assert.strictEqual(state.recordFailure('mobile', ''), 'Scene process failed. Open the run log for details.');

// A Run capture may arrive before the released drag's POST reaches the bridge.
const delayed = new State([]);
const moving = [{mesh: 'milk.stl', x: 0, y: 0, z: 0}];
delayed.authoredPosition('milk.stl', [3.877, 0.584, 0.086]);
delayed.capture(moving, {'milk.stl': [1, 2, 3, 0, 0, 0, 1]});
assert.deepStrictEqual([moving[0].x, moving[0].y, moving[0].z], [3.877, 0.584, 0.086]);
delayed.capture(moving, {'milk.stl': [3.877, 0.584, 0.086, 0, 0, 0, 1]});
delayed.capture(moving, {'milk.stl': [4, 5, 6, 0, 0, 0, 1]});
assert.deepStrictEqual([moving[0].x, moving[0].y, moving[0].z], [4, 5, 6]);
delayed.authoredPosition('milk.stl', [4, 5, 6], [0, 0, Math.SQRT1_2, Math.SQRT1_2]);
delayed.capture(moving, {'milk.stl': [4, 5, 6, 0, 0, 0, 1]});
assert(Math.abs(moving[0].yaw - Math.PI / 2) < 1e-12);
