#!/usr/bin/env python3
"""Generate defense/refs.js — the deck's citation table — from the thesis bibliography.

Run after editing the .bib:  python3 make_refs.py [path/to/literature.bib]
"""
from __future__ import annotations

import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path

DEFAULT_BIB = Path.home() / "thesis/phdthesis/hassouna/literature.bib"
OUTPUT = Path(__file__).parent / "refs.js"

LATEX_REPLACEMENTS = {
    r'{\"a}': 'ä', r'{\"o}': 'ö', r'{\"u}': 'ü', r'{\"A}': 'Ä', r'{\"O}': 'Ö',
    r'{\"U}': 'Ü', r'{\ss}': 'ß', r"{\'e}": 'é', r"{\'a}": 'á', r'{\^{}}': '^',
    '---': '—', '--': '–', '\\&': '&', '~': ' ', '\\$': '', '\\%': '%',
}
VENUE_FIELDS = ('booktitle', 'journal', 'school', 'publisher', 'howpublished')


@dataclass(frozen=True)
class Entry:
    """One bibliography record, reduced to what a slide footnote shows."""

    key: str
    """The BibTeX citation key, used as ``data-ref`` on a slide marker."""

    fields: dict[str, str]
    """The entry's raw field values, LaTeX markup already resolved."""

    def citation(self) -> str:
        """Render a compact one-line citation."""
        parts = [p for p in (self.authors(), self.title(), self.venue(), self.fields.get('year')) if p]
        return ', '.join(parts) + '.'

    def authors(self) -> str:
        """Render the author list as surnames, abbreviated past two authors."""
        raw = self.fields.get('author')
        if not raw:
            return ''
        names = [surname(a) for a in re.split(r'\s+and\s+', raw)]
        if len(names) > 2:
            return names[0] + ' et al.'
        return ' & '.join(names)

    def title(self) -> str:
        title = self.fields.get('title', '')
        return f'"{title}"' if title else ''

    def venue(self) -> str:
        for field in VENUE_FIELDS:
            if field in self.fields:
                return self.fields[field]
        if self.fields.get('type'):
            return self.fields['type']
        return ''


def surname(author: str) -> str:
    """Extract the surname from a BibTeX author name in either order."""
    author = author.strip().strip('{}')
    if ',' in author:
        return author.split(',')[0].strip()
    return author.split()[-1]


def resolve_latex(text: str) -> str:
    """Replace the LaTeX escapes the bibliography uses with plain characters."""
    for latex, plain in LATEX_REPLACEMENTS.items():
        text = text.replace(latex, plain)
    text = text.replace('{', '').replace('}', '').replace('\\', '')
    return re.sub(r'\s+', ' ', text).strip()


def parse(bib: str) -> list[Entry]:
    """Read every entry of a BibTeX file into :class:`Entry` records."""
    entries = []
    for match in re.finditer(r'@(\w+)\s*\{\s*([^,]+),(.*?)\n\}', bib, re.S):
        body = match.group(3)
        fields = {}
        for field in re.finditer(r'(\w+)\s*=\s*', body):
            fields[field.group(1).lower()] = resolve_latex(read_value(body, field.end()))
        entries.append(Entry(key=match.group(2).strip(), fields=fields))
    return entries


def read_value(body: str, start: int) -> str:
    """Read one field value beginning at *start*, keeping nested braces together."""
    if body[start] == '"':
        return body[start + 1:body.index('"', start + 1)]
    if body[start] != '{':
        return body[start:].split(',')[0]
    depth, i = 0, start
    while i < len(body):
        if body[i] == '{':
            depth += 1
        elif body[i] == '}':
            depth -= 1
            if depth == 0:
                return body[start + 1:i]
        i += 1
    raise ValueError(f'unbalanced braces in bibliography entry near offset {start}')


def main() -> None:
    bib_path = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_BIB
    table = {e.key: e.citation() for e in parse(bib_path.read_text())}
    body = ',\n'.join(f'  {json.dumps(k)}: {json.dumps(v)}' for k, v in sorted(table.items()))
    OUTPUT.write_text(
        '/* Generated by defense/make_refs.py from the thesis bibliography — do not edit by hand. */\n'
        'window.REFS = {\n' + body + '\n};\n'
    )
    print(f'{len(table)} references -> {OUTPUT}')


if __name__ == '__main__':
    main()
