"""
A Unitree G1 runs a supply round for a technician working on a wind-turbine rotor
hub in a nacelle assembly hall.

The hall holds a production line of three nacelles on assembly stands; the middle
one already carries its rotor hub and spinner, and a technician is working on it.
The robot does what mobile robots do in such plants: it brings the technician the
torque wrench and the bolt crate for the next work step from the parts supply table
in the logistics corner, and takes the empty crate at the assembly station back to
logistics on its return leg.
"""

from __future__ import annotations

import os
from dataclasses import dataclass

import numpy as np

from coraplex.datastructures.dataclasses import Context
from coraplex.datastructures.enums import Arms, ApproachDirection, VerticalAlignment
from coraplex.datastructures.grasp import GraspDescription
from coraplex.execution_environment import simulated_robot
from coraplex.plans.factories import sequential
from coraplex.plans.plan import Plan
from coraplex.robot_plans import MoveJointsMotion
from coraplex.robot_plans.actions.core.navigation import NavigateAction
from coraplex.robot_plans.actions.core.pick_up import PickUpAction
from coraplex.robot_plans.actions.core.placing import PlaceAction
from coraplex.robot_plans.actions.core.robot_body import ParkArmsAction
from coraplex.testing import start_visualization
from coraplex.view_manager import ViewManager
from semantic_digital_twin.adapters.mesh import STLParser
from semantic_digital_twin.adapters.package_resolver import FileUriResolver
from semantic_digital_twin.api import RobotSpecification, WorldSpecification
from semantic_digital_twin.robots.unitree_g1 import UnitreeG1
from semantic_digital_twin.spatial_types.spatial_types import Pose
from semantic_digital_twin.world import World

# %% where everything stands in the hall

HALL_URDF = os.path.join(os.path.dirname(__file__), "wind_turbine_hall.urdf")
"""
The nacelle assembly hall the demo plays in.
"""

PELVIS_HEIGHT_ABOVE_FLOOR = 0.7923
"""
How far the G1's pelvis stands above the floor with all of its leg joints at zero.

The pelvis is the robot's root, so its ``odom`` has to be lifted by this much for the
robot's feet to rest on the floor rather than sink through it.
"""

ROBOT_START_POSE = Pose.from_xyz_rpy(6.5, 0.4, PELVIS_HEIGHT_ABOVE_FLOOR)
"""
Where the robot starts, in the logistics lane between the supply table and the
assembly line.
"""

SUPPLY_TABLE_HEIGHT = 0.75
"""
Top of the parts supply table in the logistics corner.
"""

DELIVERY_TABLE_HEIGHT = 0.78
"""
Top of the delivery table at the assembly station.
"""

STANDING_DISTANCE = 0.6
"""
How far the robot stands from a pose, in meters, opposite its FRONT-facing side.

Within the G1's reach, and far enough from a table to leave its footprint free.
"""

DELIVERY_APPROACH_YAW = -np.pi / 2
"""
Poses on the delivery table face south, so the robot approaches the table from the
logistics lane.
"""


@dataclass
class TransportTask:
    """
    One item the robot moves between the supply table and the assembly station.

    Each item is a real mesh generated by ``generate_hall_meshes.py``, so a torque
    wrench looks like a torque wrench in the visualization.
    """

    mesh_name: str
    """
    File name of the item's mesh under ``meshes/``, which is also its body name.
    """

    half_height: float
    """
    Half of the mesh's z extent, so spawn poses rest the item on a table surface.
    """

    pick_pose: Pose
    """
    Where the item waits when the robot comes to fetch it.
    """

    place_pose: Pose
    """
    Where the robot puts the item down.
    """


def supply_pose(y: float, item_height: float) -> Pose:
    """
    :param y: The pose's y coordinate along the supply table.
    :param item_height: The item's z extent.
    :return: The pose of the item resting on the supply table at that spot.
    """
    return Pose.from_xyz_rpy(8.5, y, SUPPLY_TABLE_HEIGHT + item_height / 2)


def delivery_pose(x: float, item_height: float) -> Pose:
    """
    :param x: The pose's x coordinate along the delivery table.
    :param item_height: The item's z extent.
    :return: The pose of the item resting on the delivery table at that spot.
    """
    return Pose.from_xyz_rpy(
        x,
        -0.9,
        DELIVERY_TABLE_HEIGHT + item_height / 2,
        yaw=DELIVERY_APPROACH_YAW,
    )


TORQUE_WRENCH_HALF_HEIGHT = 0.0268
"""
Half the torque wrench mesh's z extent.
"""

CRATE_HALF_HEIGHT = 0.045
"""
Half the load carrier meshes' z extent.
"""

TASKS = [
    TransportTask(
        mesh_name="torque_wrench.stl",
        half_height=TORQUE_WRENCH_HALF_HEIGHT,
        pick_pose=supply_pose(3.15, 2 * TORQUE_WRENCH_HALF_HEIGHT),
        place_pose=delivery_pose(-0.15, 2 * TORQUE_WRENCH_HALF_HEIGHT),
    ),
    TransportTask(
        mesh_name="bolt_crate.stl",
        half_height=CRATE_HALF_HEIGHT,
        pick_pose=supply_pose(3.50, 2 * CRATE_HALF_HEIGHT),
        place_pose=delivery_pose(0.30, 2 * CRATE_HALF_HEIGHT),
    ),
    TransportTask(
        mesh_name="empty_crate.stl",
        half_height=CRATE_HALF_HEIGHT,
        pick_pose=delivery_pose(0.75, 2 * CRATE_HALF_HEIGHT),
        place_pose=supply_pose(3.90, 2 * CRATE_HALF_HEIGHT),
    ),
]
"""
The supply round: tool and material to the assembly station, empties back to
logistics.
"""

# %% building the world and the plan


def build_world() -> World:
    """
    :return: The assembly hall with the G1 and all transported items in it.
    """
    world = WorldSpecification.from_urdf(
        HALL_URDF,
        path_resolver=FileUriResolver(base_directory=os.path.dirname(HALL_URDF)),
        robots=[
            RobotSpecification(
                semantic_annotation_type=UnitreeG1,
                world_T_odom=ROBOT_START_POSE.to_homogeneous_matrix(),
            )
        ],
    ).to_domain_object()
    for task in TASKS:
        item_world = STLParser(
            os.path.join(os.path.dirname(HALL_URDF), "meshes", task.mesh_name)
        ).parse()
        world.merge_world_at_pose(item_world, task.pick_pose.to_homogeneous_matrix())
    return world


def standing_pose_in_front_of(pose: Pose, world: World) -> Pose:
    """
    :param pose: The pose the robot should approach from its FRONT-facing side.
    :param world: The world the pose is expressed in.
    :return: The pose the robot stands in to reach that pose with a FRONT grasp.
    """
    yaw = float(pose.yaw)
    return Pose.from_xyz_rpy(
        pose.x - STANDING_DISTANCE * np.cos(yaw),
        pose.y - STANDING_DISTANCE * np.sin(yaw),
        PELVIS_HEIGHT_ABOVE_FLOOR,
        yaw=yaw,
        reference_frame=world.root,
    )


def turn_between(pick_pose: Pose, place_pose: Pose) -> float:
    """
    :param pick_pose: The pose the robot faced while picking.
    :param place_pose: The pose the robot will face while placing.
    :return: The relative yaw, wrapped to ``[-pi, pi]``, turning the robot from the
        pick approach towards the place approach before it drives off.
    """
    difference = float(place_pose.yaw) - float(pick_pose.yaw)
    return float(np.arctan2(np.sin(difference), np.cos(difference)))


def build_transport_plan(world: World, robot: UnitreeG1, task: TransportTask) -> Plan:
    """
    :param world: The world the plan acts in.
    :param robot: The robot carrying out the plan.
    :param task: The item to fetch and where to bring it.
    :return: The plan moving that item across the hall.
    """
    item = world.get_body_by_name(task.mesh_name)
    grasp = GraspDescription(
        ApproachDirection.FRONT,
        VerticalAlignment.NoAlignment,
        ViewManager.get_end_effector_view(Arms.LEFT, robot),
    )
    context = Context(world=world, robot=robot, evaluate_conditions=False)
    place_pose = Pose(
        task.place_pose.to_position(),
        task.place_pose.to_quaternion(),
        reference_frame=world.root,
    )
    torso_connection_names = [
        connection.name for connection in robot.torso.active_connections
    ]

    return sequential(
        [
            # %% fetch the item and bring it to the other end of the hall
            ParkArmsAction(Arms.BOTH),
            NavigateAction(standing_pose_in_front_of(task.pick_pose, world)),
            PickUpAction(item, Arms.LEFT, grasp),
            ParkArmsAction(Arms.BOTH),
            MoveJointsMotion(
                names=torso_connection_names,
                positions=[0.0] * len(torso_connection_names),
            ),
            NavigateAction(
                Pose.from_xyz_rpy(
                    yaw=turn_between(task.pick_pose, task.place_pose),
                    reference_frame=robot.root,
                )
            ),
            NavigateAction(standing_pose_in_front_of(task.place_pose, world)),
            PlaceAction(item, place_pose, Arms.LEFT),
            ParkArmsAction(Arms.BOTH),
            MoveJointsMotion(
                names=torso_connection_names,
                positions=[0.0] * len(torso_connection_names),
            ),
        ],
        context=context,
    ).plan


def lowest_collision_point_of(robot: UnitreeG1, world: World) -> float:
    """
    :param robot: The robot to measure.
    :param world: The world the height is expressed in.
    :return: The height of the robot's lowest collision geometry above the hall floor.
    """
    return min(
        body.collision.as_bounding_box_collection_in_frame(world.root)
        .bounding_box()
        .min_z
        for body in world.get_kinematic_structure_entities_of_branch(robot.root)
        if body.collision
    )


# %% running the demo

world = build_world()
robot = world.get_semantic_annotations_by_type(UnitreeG1)[0]
# Keeps PELVIS_HEIGHT_ABOVE_FLOOR honest: the robot has to stand on the floor rather
# than sink into it or hover above it.
assert abs(lowest_collision_point_of(robot, world)) < 1e-3

start_visualization(world)

with simulated_robot:
    for task in TASKS:
        build_transport_plan(world, robot, task).perform()

for task in TASKS:
    item_position = world.get_body_by_name(task.mesh_name).global_pose
    print(
        "%s moved to %s, expected %s"
        % (
            task.mesh_name,
            np.round(item_position.to_position(), 3),
            np.round(task.place_pose.to_position(), 3),
        )
    )
    assert np.allclose(item_position, task.place_pose, atol=0.05)
