"""
Pre-commit entry point that truncates generated ORM interface files to zero bytes.

Every ``ormatic_interface.py`` is generated by ORMatic (see
``scripts/regenerate_all_orm.py`` and each package's ``scripts/generate_orm.py``) and is
never reviewed, so the repository only tracks it as an empty placeholder. Whenever one
of these files is staged with real content (for example because a developer regenerated
it locally for database work), this hook rewrites it back to empty before the commit is
created.
"""

from __future__ import annotations

import sys
from pathlib import Path
from typing_extensions import Sequence


def empty_file(path: Path) -> None:
    """
    Truncate the file at ``path`` to zero bytes without deleting it.

    :param path: File to truncate.
    """
    path.write_text("", encoding="utf-8")


def main(paths: Sequence[str]) -> int:
    """
    Truncate every given path to an empty file.

    :param paths: Paths to generated ORM interface files, as passed by pre-commit.
    :return: Process exit code.
    """
    for path in paths:
        empty_file(Path(path))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
