"""
Regenerate the ORM interfaces of every package that has one.

Runnable from any working directory: all paths are resolved relative to this file.
"""

from __future__ import annotations

import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

from protect_generated_orm_interfaces import mark_skip_worktree

REPOSITORY_ROOT = Path(__file__).resolve().parents[1]


@dataclass
class OrmPackage:
    """
    A workspace package whose ORM interface is generated by its own script.
    """

    name: str
    """
    Name of the package, which is also the name of its source folder and module.
    """

    @property
    def generator(self) -> Path:
        """
        The script that regenerates this package's ORM interface.
        """
        return REPOSITORY_ROOT / self.name / "scripts" / "generate_orm.py"

    @property
    def interface(self) -> Path:
        """
        The generated ORM interface file.
        """
        return (
            REPOSITORY_ROOT
            / self.name
            / "src"
            / self.name
            / "orm"
            / "ormatic_interface.py"
        )

    def clear_interface(self) -> None:
        """
        Empty the generated interface without deleting the file, so that a stale version
        cannot be imported while the new one is being generated.
        """
        if not self.interface.exists():
            raise FileNotFoundError(f"Interface not found: {self.interface}")
        self.interface.write_text("", encoding="utf-8")

    def regenerate(self) -> None:
        """
        Run this package's generator in a subprocess.
        """
        if not self.generator.exists():
            raise FileNotFoundError(f"Generator not found: {self.generator}")
        subprocess.run(
            [sys.executable, str(self.generator)],
            cwd=self.generator.parent,
            check=True,
        )


# Ordered by dependency: each package's generator imports the interfaces of the
# packages listed before it.
ORM_PACKAGES = [
    OrmPackage("semantic_digital_twin"),
    OrmPackage("giskardpy"),
    OrmPackage("coraplex"),
    OrmPackage("segmind"),
    OrmPackage("experiments"),
]


def main() -> None:
    for package in ORM_PACKAGES:
        package.clear_interface()

    for package in ORM_PACKAGES:
        package.regenerate()

    # Regenerated interfaces have real, unreviewed content again; keep git from ever
    # proposing to commit that content by ignoring local changes to these paths.
    for package in ORM_PACKAGES:
        mark_skip_worktree(str(package.interface.relative_to(REPOSITORY_ROOT)))


if __name__ == "__main__":
    main()
