"""
A Toyota HSR runs a sample-analysis round through a chemical laboratory.

The laboratory holds a long preparation bench along the west wall, a central
analysis island crowded with glassware, and two scientist desks by the east wall.
The robot does what a laboratory assistant robot does between experiments: it
carries the incoming sample flask from the preparation bench to the analysis
island, brings the requested reagent bottle from the island to the scientist's
desk, and returns the empty test-tube rack from the island to the preparation
bench on its way back.
"""

from __future__ import annotations

import os
from dataclasses import dataclass

import numpy as np
from typing_extensions import Optional

from coraplex.datastructures.dataclasses import Context
from coraplex.datastructures.enums import (
    Arms,
    ApproachDirection,
    VerticalAlignment,
    VisualizationBackend,
)
from coraplex.datastructures.grasp import GraspDescription
from coraplex.execution_environment import simulated_robot
from coraplex.plans.attachment_nodes import AttachNode, DetachNode
from coraplex.plans.factories import sequential
from coraplex.plans.plan import Plan
from coraplex.plans.plan_node import PlanNode
from coraplex.robot_plans.actions.core.navigation import NavigateAction
from coraplex.robot_plans.actions.core.pick_up import PickUpAction
from coraplex.robot_plans.actions.core.placing import PlaceAction
from coraplex.robot_plans.actions.core.robot_body import ParkArmsAction
from coraplex.view_manager import ViewManager
from coraplex.visualization import WorldVisualization
from semantic_digital_twin.adapters.mesh import STLParser
from semantic_digital_twin.adapters.package_resolver import FileUriResolver
from semantic_digital_twin.api import RobotSpecification, WorldSpecification
from semantic_digital_twin.robots.hsrb import HSRB
from semantic_digital_twin.spatial_types.spatial_types import Pose
from semantic_digital_twin.world import World
from semantic_digital_twin.world_description.world_entity import Body

# %% where everything stands in the laboratory

LABORATORY_URDF = os.path.join(os.path.dirname(__file__), "chemical_laboratory.urdf")
"""
The chemical laboratory the demo plays in.
"""

ROBOT_START_POSE = Pose.from_xyz_rpy(1.2, -2.4, 0, yaw=np.pi / 2)
"""
Where the robot starts, on the open floor between the analysis island and the
scientist desks.
"""

WORK_SURFACE_HEIGHT = 0.9
"""
Top of the preparation bench, the analysis island and the scientist desks; every
work surface of this laboratory is bench-high.
"""

STANDING_DISTANCE = 0.6
"""
How far the robot's base stands from a pose it works on, in meters, opposite the
pose's approach direction.

Within the HSR's arm reach, and far enough from a bench to leave its footprint free.
"""

WEST_APPROACH_YAW = np.pi
"""
Poses on the preparation bench and on the island's east flank face east, so the
robot approaches them from the room's open middle.
"""

EAST_APPROACH_YAW = 0.0
"""
Poses on the scientist desk face west, so the robot approaches the desk from the
open floor in front of it.
"""


@dataclass
class TransportTask:
    """
    One item the robot moves between the laboratory's work surfaces.

    Each item is a real mesh generated by ``generate_laboratory_items.py``, so a
    flask looks like a flask in the visualization.
    """

    mesh_name: str
    """
    File name of the item's mesh under ``meshes/``, which is also its body name.
    """

    half_height: float
    """
    Half of the mesh's z extent, so spawn poses rest the item on a work surface.
    """

    pick_pose: Pose
    """
    Where the item waits when the robot comes to fetch it.
    """

    place_pose: Pose
    """
    Where the robot puts the item down.
    """


def surface_pose(x: float, y: float, item_height: float, yaw: float) -> Pose:
    """
    :param x: The pose's x coordinate.
    :param y: The pose's y coordinate.
    :param item_height: The item's z extent.
    :param yaw: The direction the pose is approached from, pointing towards the robot.
    :return: The pose of the item resting on the work surface at that spot.
    """
    return Pose.from_xyz_rpy(x, y, WORK_SURFACE_HEIGHT + item_height / 2, yaw=yaw)


SAMPLE_FLASK_HALF_HEIGHT = 0.0575
"""
Half the sample flask mesh's z extent.
"""

REAGENT_BOTTLE_HALF_HEIGHT = 0.075
"""
Half the reagent bottle mesh's z extent.
"""

TEST_TUBE_RACK_HALF_HEIGHT = 0.045
"""
Half the test tube rack mesh's z extent.
"""

TASKS = [
    TransportTask(
        mesh_name="sample_flask.stl",
        half_height=SAMPLE_FLASK_HALF_HEIGHT,
        pick_pose=surface_pose(
            -2.45, -0.75, 2 * SAMPLE_FLASK_HALF_HEIGHT, WEST_APPROACH_YAW
        ),
        place_pose=surface_pose(
            0.35, -0.15, 2 * SAMPLE_FLASK_HALF_HEIGHT, WEST_APPROACH_YAW
        ),
    ),
    TransportTask(
        mesh_name="reagent_bottle.stl",
        half_height=REAGENT_BOTTLE_HALF_HEIGHT,
        pick_pose=surface_pose(
            0.35, 0.10, 2 * REAGENT_BOTTLE_HALF_HEIGHT, WEST_APPROACH_YAW
        ),
        place_pose=surface_pose(
            2.30, 1.25, 2 * REAGENT_BOTTLE_HALF_HEIGHT, EAST_APPROACH_YAW
        ),
    ),
    TransportTask(
        mesh_name="test_tube_rack.stl",
        half_height=TEST_TUBE_RACK_HALF_HEIGHT,
        pick_pose=surface_pose(
            0.35, -1.20, 2 * TEST_TUBE_RACK_HALF_HEIGHT, WEST_APPROACH_YAW
        ),
        place_pose=surface_pose(
            -2.45, -1.60, 2 * TEST_TUBE_RACK_HALF_HEIGHT, WEST_APPROACH_YAW
        ),
    ),
]
"""
The analysis round: the sample to the island, the reagent to the scientist, the
empty rack back to the preparation bench.
"""

# %% grasping in a world without physics

# This demo's world is purely kinematic: nothing holds a grasped item between the
# fingers, so the world model itself has to carry the item along with the gripper.


@dataclass
class ModelAttachingPickUpAction(PickUpAction):
    """
    A pick-up that also attaches the grasped object to the gripper's tool frame in
    the world model, so the object follows the gripper in a world without
    physics-based holding.
    """

    def _grasp_attempt_plan(self) -> PlanNode:
        return sequential(
            children=[
                super()._grasp_attempt_plan(),
                AttachNode(
                    body=self.object_designator,
                    new_parent=ViewManager.get_end_effector_view(
                        self.arm, self.robot
                    ).tool_frame,
                ),
            ],
        )


@dataclass
class ModelDetachingPlaceAction(PlaceAction):
    """
    A place that also re-parents the placed object back to the world root before the
    gripper retracts, so the retraction does not drag the object along in a world
    without physics-based holding.
    """

    def _retract_plan(self, retract_pose: Pose) -> PlanNode:
        return sequential(
            children=[
                DetachNode(body=self.object_designator),
                super()._retract_plan(retract_pose),
            ],
        )


# %% building the world and the plan


def build_world() -> World:
    """
    :return: The laboratory with the HSR and all transported items in it.
    """
    world = WorldSpecification.from_urdf(
        LABORATORY_URDF,
        path_resolver=FileUriResolver(base_directory=os.path.dirname(LABORATORY_URDF)),
        robots=[
            RobotSpecification(
                semantic_annotation_type=HSRB,
                world_T_odom=ROBOT_START_POSE.to_homogeneous_matrix(),
            )
        ],
    ).to_domain_object()
    for task in TASKS:
        item_world = STLParser(
            os.path.join(os.path.dirname(LABORATORY_URDF), "meshes", task.mesh_name)
        ).parse()
        world.merge_world_at_pose(item_world, task.pick_pose.to_homogeneous_matrix())
    return world


def standing_pose_in_front_of(pose: Pose, world: World) -> Pose:
    """
    :param pose: The pose the robot should approach from its FRONT-facing side.
    :param world: The world the pose is expressed in.
    :return: The pose the robot stands in to reach that pose with a FRONT grasp.
    """
    yaw = float(pose.yaw)
    return Pose.from_xyz_rpy(
        pose.x - STANDING_DISTANCE * np.cos(yaw),
        pose.y - STANDING_DISTANCE * np.sin(yaw),
        0,
        yaw=yaw,
        reference_frame=world.root,
    )


def build_transport_plan(world: World, robot: HSRB, task: TransportTask) -> Plan:
    """
    :param world: The world the plan acts in.
    :param robot: The robot carrying out the plan.
    :param task: The item to fetch and where to bring it.
    :return: The plan moving that item across the laboratory.
    """
    item = world.get_body_by_name(task.mesh_name)
    grasp = GraspDescription(
        ApproachDirection.FRONT,
        VerticalAlignment.NoAlignment,
        ViewManager.get_end_effector_view(Arms.LEFT, robot),
    )
    context = Context(world=world, robot=robot, evaluate_conditions=False)
    place_pose = Pose(
        task.place_pose.to_position(),
        task.place_pose.to_quaternion(),
        reference_frame=world.root,
    )

    return sequential(
        [
            # %% fetch the item and bring it to its destination
            ParkArmsAction(Arms.BOTH),
            NavigateAction(standing_pose_in_front_of(task.pick_pose, world)),
            ModelAttachingPickUpAction(item, Arms.LEFT, grasp),
            ParkArmsAction(Arms.BOTH),
            NavigateAction(standing_pose_in_front_of(task.place_pose, world)),
            ModelDetachingPlaceAction(item, place_pose, Arms.LEFT),
            ParkArmsAction(Arms.BOTH),
        ],
        context=context,
    ).plan


def lowest_collision_point_of(robot: HSRB, world: World) -> float:
    """
    :param robot: The robot to measure.
    :param world: The world the height is expressed in.
    :return: The height of the robot's lowest collision geometry above the floor.
    """
    return min(
        body.collision.as_bounding_box_collection_in_frame(world.root)
        .bounding_box()
        .min_z
        for body in world.get_kinematic_structure_entities_of_branch(robot.root)
        if body.collision
    )


# %% running the demo

world = build_world()
robot = world.get_semantic_annotations_by_type(HSRB)[0]
# The robot has to stand on the floor rather than sink into it or hover above it.
assert abs(lowest_collision_point_of(robot, world)) < 1e-2

# The browser viewer by default; CORAPLEX_VISUALIZATION still overrides per run.
visualization = WorldVisualization.from_environment(
    world, default_backend=VisualizationBackend.CRAMERA
).start()

with simulated_robot:
    for task in TASKS:
        plan = build_transport_plan(world, robot, task)
        visualization.attach_plan(plan)
        plan.perform()

for task in TASKS:
    item_position = world.get_body_by_name(task.mesh_name).global_pose
    print(
        "%s moved to %s, expected %s"
        % (
            task.mesh_name,
            np.round(item_position.to_position(), 3),
            np.round(task.place_pose.to_position(), 3),
        )
    )
    assert np.allclose(item_position, task.place_pose, atol=0.05)
